### PR TITLE
Remote shell should not terminate the remote node on EOF

### LINKED ISSUE #9852: remsh stoping the main vm when closing stdin.
**Describe the bug**
Remsh is terminating the remote process when it isn't supposed to.

**To Reproduce**

Terminal 1

```
erl -sname node1
```

Terminal 2

```
erl -sname node2 -remsh node1 < /dev/null
```

The process in terminal 2 keeps open and the one in terminal 1 stops.

**Expected behavior**
The process in terminal 1 should not terminate and the terminal 2 process should terminate.

**Affected versions**
OTP 26+

**Additional context**
Tested on 25.2.1 (works as expected), 26.2.5.12 (doesn't work) and 27.3.4 (doesn't work)

### PR DESCRIPTION
**Pull request by frazze-jobb**
Closes #9852

### CODE REVIEW

File: lib/kernel/src/user_drv.erl [hunk 1]
```diff
@@ -550,10 +550,25 @@ server(info,{'EXIT', Group, Reason}, State) -> % shell and group leader exit
                                               current_group = NewGroup,
                                               groups = Gr2 }};
                 _ -> % remote shell
-                    NewTTYState = io_requests(
-                                    Reqs ++ [{put_chars,unicode,<<"(^G to start new job) ***\n">>}],
-                                    State#state.tty),
-                    {keep_state, State#state{ tty = NewTTYState, groups = Gr1 }}
+                    %% If the readhandle has terminated, then we should quit
+                    case State#state.read =:= eof of
```
Comment (garazdawi) [inline lib/kernel/src/user_drv.erl:554]: Is this code to make sure the remote node is also terminated?

Can we add tests for this?

Comment (frazze-jobb) [reply lib/kernel/src/user_drv.erl:554]: When state.read =:= eof is true, then we want the local node to terminate, because it's the local node's readhandle that received the EOF. The remote node should still be alive.
When state.read =:= eof is false, then the remote node has terminated. The local node should remove its "remote shell group".
