### PR TITLE
Avoid optimization that beam_validator might consider unsafe

### LINKED ISSUE #6599: [erlc] internal consistency check failed: "illegal_branch, try_handler"
On master,
```erlang
f(X, #{0 := X, 0 := Y}) ->
    try #{ok => ok} of
        Y ->
            bnot (Y = X)
    after
        ok
    end.
```
crashes erlc with the message:
```
consistency_try:1: function f/2+13:
  Internal consistency check failed - please report this bug.
  Instruction: {jump,{f,8}}
  Error:       {illegal_branch,try_handler,8}:
```

### PR DESCRIPTION
**Pull request by bjorng**
Eliminating a repeated `=:=` test can result in code that `beam_validator` doesn't consider safe. This pull request makes the optimization keep `=:=` if it seems to be significant, that is, if one or both operands will gain type information from it.
    
That makes it possible to compile code from #6599 such as:
    
        f(X, X) when is_integer(X) ->
            ok;
        f(Y, Y = #{}) ->
            Y#{ok := ok}.
    
(Six other examples from #6599 can now also be compiled.)
    
Running `scripts/diffable` shows that this fix prevented the optimization in 14 modules (out of about 1000).
    
Closes #6599 (the examples that were not fixed by this PR will be transferred to a new issue)

### CODE REVIEW

File: lib/compiler/src/beam_ssa_dead.erl [hunk 1]
```diff
@@ -1187,6 +1197,33 @@ opt_redundant_tests_is([I|Is], Tests, Acc) ->
...
+        0 ->
+            false;
+        1 ->
+            true;
+        2 ->
+            case Types of
+                #{0 := Same,1 := Same} ->
+                    false;
+                #{} ->
+                    true
```
Comment (kikofernandez) [inline lib/compiler/src/beam_ssa_dead.erl:1215]: this case was already covered by `map_size/1`, which would fall under the `0` size case.
so it cannot be that `#{}` is reachable, because `map_size(Types)` rules it out. At the same time, when size is 0 we return false, and when size is 0 for #{} we return true. 

I think there is something that may not be correct?
