### PR TITLE
Correct sockname handling for DTLS

### LINKED ISSUE #10097: sockname failed on dtls
**Describe the bug**
ssl:sockname failed on ssl:connect using dtls

**To Reproduce**
Use attached module dtls_sockname:test()

**Expected behavior**
ssl:sockname should return Address and Port of dtls-connection

**Affected versions**
Tested on OTP 26 and OTP 28

**dtls_sockname.erl**

`
-module(dtls_sockname).
-author("cordaware").

-include_lib("ssl/src/ssl_api.hrl").

%% API
-export([dtls_listen/1,dtls_connect/2,test/0]).

test() -> ssl:start(), test(inet),test(socket).

test(Backend) ->
  {_Pid,Ref1} = spawn_monitor(?MODULE, dtls_listen, [Backend]),
  receive
    {'DOWN', Ref1, _, _, _} -> ok
  end.

lookup(psk,S,_C) -> {ok,S}.

%% <= OTP28 comment out on OTP28
%%mysockname(#sslsocket{pid = [Pid|_], fd = {Transport, {_AddrPort,Socket}, _}}) when is_pid(Pid) ->
%%  dtls_socket:sockname(Transport, Socket).

%% >= OTP28 comment out on OTP26
mysockname(#sslsocket{connection_handler = Controller,
  connection_cb = dtls_gen_connection,
  transport_cb = Transport,
  socket_handle = {_AddrPort,Socket}}) when is_pid(Controller) ->
  dtls_socket:sockname(Transport, Socket).

dtls_connect(Port,Backend) ->
  {ok,S} = ssl:connect("127.0.0.1", Port, [
    {inet_backend,Backend},
    {protocol,'dtls'},
    {psk_identity,"psk"},
    {verify,verify_none},
    {user_lookup_fun,{fun lookup/3,"psk"}},
    {versions,['dtlsv1.2']},
    {ciphers, [{dhe_psk,aes_256_gcm,null,sha384}]}]),
  SN0 = mysockname(S),
  io:format("dtls(~p) sockname should be ~p~n", [Backend,{SN0,S}]),
  try
    {ok,SN1} = ssl:sockname(S),
    io:format("dtls(~p) sockname ok ~p~n", [Backend,{SN1,S}])
  catch
    E:Msg ->
      io:format("dtls(~p) sockname failed ~p~n", [Backend,{{E,Msg},S}])
  end.

dtls_listen(Backend) ->
  {ok,S} = ssl:listen(0,[
    {inet_backend,Backend},
    {protocol,'dtls'},
    {psk_identity,"psk"},
    {verify,verify_none},
    {user_lookup_fun,{fun lookup/3,"psk"}},
    {versions,['dtlsv1.2']},
    {ciphers, [{dhe_psk,aes_256_gcm,null,sha384}]}]),
  {ok, {_, LPort}} = ssl:sockname(S),
  {_Pid,Ref} = spawn_monitor(?MODULE, dtls_connect, [LPort,Backend]),
  {ok, ASock} = ssl:transport_accept(S),
  {ok, _SslSocket} = ssl:handshake(ASock),
  receive
    {'DOWN', Ref, _, _, _} -> ok
  end.
`

### PR DESCRIPTION
**Pull request by IngelaAndin**
Closes #10097

### CODE REVIEW

File: lib/ssl/test/dtls_api_SUITE.erl [hunk 1]
```diff
@@ -568,6 +573,38 @@ client_restarts_multiple_acceptors(Config) ->
...
+    {ClientNode, ServerNode, Hostname} = ssl_test_lib:run_where(Config),
+    Server = ssl_test_lib:start_server([{node, ServerNode}, {port, 0},
+					{from, self()},
+			   {mfa, {ssl, sockname, []}},
+			   {options, ServerOpts}]),
+    Port = ssl_test_lib:inet_port(Server),
+    Client = ssl_test_lib:start_client([{node, ClientNode}, {port, Port},
+					{host, Hostname},
+                                        {from, self()},
+                                        {mfa, {ssl, sockname, []}},
```
Comment (u3s) [inline lib/ssl/test/dtls_api_SUITE.erl:590]: not sure if it matters, but this mfa option will result with running ssl:sockname with AcceptSocket as arg.
whereas, code provided in the issue used socket returned from ssl:listen - also this is what you added in dtls socket?

is this relevant?
maybe both sockets should be tested?

**Review by u3s — CHANGES_REQUESTED** [review]
pls check comment inline

File: lib/ssl/test/dtls_api_SUITE.erl (hunk 1 above)
Comment (IngelaAndin) [reply lib/ssl/test/dtls_api_SUITE.erl:590]: @u3s  No the call in the issue, that was failing, was the call using the `sslsocket `returned from connect. So not relevant.
Covered in ssl_api_SUITE!

**Review by u3s — APPROVED** [review]
