### PR TITLE
Fix win32reg issues #5037 and #4702

### LINKED ISSUE #5037: win32reg:value/2 fails to get default value ('default' or "")
The function win32reg:value/2 cannot be used to get the default value of a registry key.  
- Passing 'default' results in `Bad value on output port 'registry__drv__ wr'`
- Passing "" results in `error:{case_clause,{value,{default,"test"}}} at [{win32reg,value,2,[{file,"win32reg.erl"},{line,175}]},`

The expected outcome is `{ok, Value}` when a value exists.

This affects OTP 24.0

I have a pull request #5038 which should fix this issue, as well as #4702 and I also noticed a weakness in change_key/2 when passed a relative path of .. and at the "top" of the tree.

### PR DESCRIPTION
**Pull request by reganheath**
Pull request to resolve #5037 and #4702 (issues with win32reg).  I have to be honest, I found it very hard to debug and test this due to the complexity of building OTP on windows.  I managed to build it in WSL, but of course this doesn't help as the code in Q is windows only.

### CODE REVIEW

**Comment by garazdawi** [comment]
Hello! Github actions build windows installers that you can download and test your changes with. If you click on the [actions](https://github.com/erlang/otp/pull/5038/checks) tabs there is an artifacts dropdown where you can download `otp_prebuilt_win32`.

**Comment by reganheath** [comment]
Awesome.  I have downloaded the windows installer, installed it on a clean VM, then run my test cases in an escript.  I found one mistake, corrected it, and I believe the changes are good.

File: erts/emulator/drivers/win32/registry_drv.c [hunk 1]
```diff
@@ -318,8 +318,12 @@ reg_from_erlang(ErlDrvData clientData, char* buf, ErlDrvSizeT count)
...
 	break;
     case CMD_DELETE_KEY:
-	result = RegDeleteKey(rp->hkey, NULL);
-	reply(rp, result);
+	{
+	    char* key = buf;
+
+	    result = RegDeleteKey(rp->hkey, key);
+	    reply(rp, result);
+	}
```
Comment (sverker) [inline erts/emulator/drivers/win32/registry_drv.c:326]: I don't get how this could work (other than pure luck). The data buffer sent for CMD_DELETE_KEY does only contain one byte (the value 7). The pointer `buf` has been incremented (before the `switch`) to point just beyond that first and only byte into unknown territory. Passing it as argument to any function is just wrong.

According to `RegDeleteKey` documentation, the second argument `lpSubKey` should be the name of the subkey to be deleted.

Comment (sverker) [reply erts/emulator/drivers/win32/registry_drv.c:326]: Maybe better (as @b-winkler proposed) to replace the broken `delete_key` with a new `delete_subkey` which is simpler to implement and does not have the quirk to invalidate the current key.

Comment (reganheath) [reply erts/emulator/drivers/win32/registry_drv.c:326]: This necessitates a change in the documentation as well, which is why I avoided it initially.  If we're certain we prefer it, I can make that change.  Let me know :)

Comment (sverker) [reply erts/emulator/drivers/win32/registry_drv.c:326]: Well, if you have done a `delete_key` that actually works I'm fine with keeping it.

**Comment by sverker** [comment]
@reganheath I would prefer if you could rearrange the commits with one for each issue, `value` and `delete_key`.

Also you should describe the actual fix in the commit headline, like "Fix win32reg:value/2 for default value". If referring the github issue or pull request do that with GH-5027 and PR-5038.

If you want, you could also rebase on maint ("git rebase --onto maint master") to get these fixes into OTP-24.1.

**Comment by sverker** [comment]
... and if so, also click Edit and change this PR to be based on maint.

**Comment by sverker** [comment]
Rebased on maint and put into test.

**Comment by sverker** [comment]
Added `win32reg:change_key(Reg, "\\hkcu")` in the new tests to try fix failures with {error, eacces} on our test machines.

**Comment by reganheath** [comment]
Sorry!  I've been swamped with stuff recently.

**Comment by sverker** [comment]
Merged to maint for 24.1.
Thanks for the contribution.
