### PR TITLE
debugger: Fix incorrect evaluation of nested records in guard

### LINKED ISSUE #8120: Debugger records comparison bug
The following code works when compiled but not when run in `int`.

```erlang
-module(a_test).

%% This test works in OTP 22, but it fails in OTP 25 and OTP 26.
%%
%% Run this in the Erlang shell to reproduce it:
%%
%%   1> a_test:the_test().
%%   A TEST OK!!
%%   ok
%%   2> i:ii(a_test).
%%   {module,a_test}
%%   3> a_test:the_test().
%%   A TEST IS NOT OK!

-export([the_test/0]).

-define(is_foo(X), (((X#foo.the_baz)#baz.something == []))).

-record(baz, {something}).
-record(foo, {the_bar,
              the_baz}).
the_test() ->
    B = #baz{something = []},
    F = #foo{the_baz = B},
    if ?is_foo(F) ->
            io:format("A TEST OK!!~n",[]);
       true ->
            io:format("A TEST IS NOT OK!~n",[])
    end.
```

### PR DESCRIPTION
**Pull request by bjorng**
Closes #8120

### CODE REVIEW

File: lib/debugger/src/dbg_ieval.erl [hunk 1]
```diff
@@ -466,6 +466,7 @@ do_eval_function(Mod, Name, As0, Bs0, Called, Ieval0) ->
     Ieval = Ieval0#ieval{module=Mod,function=Name,arguments=As0},
     case get_function(Mod, Name, As0, Called) of
 	[{clause,FcLine,_,_,_}|_]=Cs ->
+            io:format("~p\n", [Cs]),
```
Comment (michalmuskala) [inline lib/debugger/src/dbg_ieval.erl:469]: This lokmskme left over debugging

Comment (bjorng) [reply lib/debugger/src/dbg_ieval.erl:469]: Yes, it is. Thanks!
