### PR TITLE
ssl: Fix Read, Write connection state mixup in NSS keylogging

### LINKED ISSUE #10698: CLIENT/SERVER_TRAFFIC_SECRET_N are mixed up when retrieved via keylog in connection_information
**Describe the bug**
CLIENT/SERVER_TRAFFIC_SECRET_N labels are mixed up when retrieved via ssl:connection_information(SslSocket, [keylog]).
Because of that, any application data packets after a handshake can't be decrypted using those secrets, without manually swapping the labels.

**To Reproduce**
E.g. establish a connection via 
`{ok, SslSocket} = ssl:connect(TcpSocket, [{versions, ['tlsv1.3']}, {keep_secrets, true}])`
and send some data on the socket while capturing the traffic e.g. via Wireshark.

Log the secrets obtained with
`ssl:connection_information(SslSocket, [keylog]).`
as they are and try to utilize them in decrypting the traffic.

Observe only the handshake packets being decrypted.
Swap the labels.
Observe all the packets being decrypted.

**Expected behavior**
CLIENT/SERVER_TRAFFIC_SECRET_N retrieved with correct labels.

**Affected versions**
Present since OTP 27.

**Additional context**
CLIENT/SERVER_HANDSHAKE_TRAFFIC_SECRET are fine.

### PR DESCRIPTION
**Pull request by IngelaAndin**
closes #10698

### CODE REVIEW

File: lib/ssl/src/ssl_gen_statem.erl
Comment (u3s) [inline lib/ssl/src/ssl_gen_statem.erl:2185]: consider adding a comment explaining code below. code is a bit redundant and hard to read (case is quite big and could be reduced to make understanding the point of it easier). maybe refactor code on master branch separately?

comment proposal:

% Logs TLS 1.3 traffic secrets for NSS keylog format.
%% Write secrets use local Role, read secrets use opposite_role(Role)
%% to ensure CLIENT_TRAFFIC_SECRET always refers to client->server traffic.

**Review by u3s — DISMISSED** [review]

File: lib/ssl/src/ssl_gen_statem.erl
Comment (IngelaAndin) [reply lib/ssl/src/ssl_gen_statem.erl:2185]: I added a comment

**Review by u3s — APPROVED** [review]

File: lib/ssl/test/tls_1_3_version_SUITE.erl [hunk 1]
```diff
@@ -664,16 +668,65 @@ receive_client_keylog_for_client_cert_alert() ->
...
+        public_key:pkix_test_data(#{server_chain => #{root => root_key(SHA),
+                                                      intermediates => intermediates(SHA, 1),
+                                                      peer => peer_key(SHA)},
+                                    client_chain => #{root => root_key(SHA),
+                                                      intermediates => intermediates(SHA, 1),
+                                                      peer => peer_key(SHA)}}),
+    #{server_config := ServerOpts} =
+        public_key:pkix_test_data(#{client_chain =>
+                                        #{root => root_key(SHA),
+                                          intermedites => intermediates(SHA, 1),
```
Comment (dgud) [inline lib/ssl/test/tls_1_3_version_SUITE.erl]:
```suggestion
                                          intermediates => intermediates(SHA, 1),
```

File: lib/ssl/test/tls_1_3_version_SUITE.erl [hunk 2]
```diff
@@ -664,16 +668,65 @@ receive_client_keylog_for_client_cert_alert() ->
...
+                                          peer => peer_key(SHA)},
+                                    server_chain =>
+                                        #{root => root_key(SHA, ssl_test_lib:pss_params(SHA)),
+                                          intermedites => intermediates(SHA,
```
Comment (dgud) [inline lib/ssl/test/tls_1_3_version_SUITE.erl]: Since these are spelled wrong and the testcase still work is it testing what you think they are testing?

```suggestion
                                          intermediates => intermediates(SHA,
```

Comment (IngelaAndin) [reply lib/ssl/test/tls_1_3_version_SUITE.erl]: Fixed it, actually I think the test worked anyway with default from public_key. This was not an important detail. But it can be good for tests not to rely too much on defaults.

File: lib/ssl/test/tls_1_3_version_SUITE.erl (hunk 1 above)
Comment (IngelaAndin) [reply lib/ssl/test/tls_1_3_version_SUITE.erl]: see comment  below
