### PR TITLE
Fix heap allocation for matching out short bitstrings

### LINKED ISSUE #7292: Overrun stack and heap OTP-26.0
**Describe the bug**
Application down few seconds after the run release in AWS eks

**To Reproduce**
Unfortunately i have no idea how to reproduce.

**Affected versions**
26.0

**Additional context**
AWS EKS
erlang 26.0
alpine 3.18.0

Application logs
```
hend=0x00007f4f6f34c7f0
stop=0x00007f4f6f34c670
htop=0x00007f4f6f34c678
heap=0x00007f4f6f349600
beam/erl_gc.c, line 735: <0.3141.0>: Overrun stack and heap
```

### PR DESCRIPTION
**Pull request by bjorng**
The runtime system could underestimate the amount of heap space needed for matching out short bitstrings with a size not divisble by 8. That could lead to the runtime system terminating with an "Overrun heap and stack" error.

Fixes #7292

### CODE REVIEW

File: erts/emulator/test/bs_match_bin_SUITE.erl [hunk 1]
```diff
@@ -280,6 +273,38 @@ do_empty_binary(0) ->
...
+                    A4:3/bits,A5:1/bits,As1/binary>>) ->
+    small_bitstring_1(As0, As1);
+small_bitstring_1(<<>>, <<>>) ->
+    ok.
+
+%%%
+%%% Common utilities.
+%%%
+
+rand_seed() ->
```
Comment (sverker) [inline erts/emulator/test/bs_match_bin_SUITE.erl:299]: I think you forgot to use utility function `rand_seed`.

**Review by sverker — APPROVED** [review]
