### PR TITLE
ssh: fix ssh_file:encode typespec

### LINKED ISSUE #10526: `ssh_file:encode` has incorrect typespec for `openssh_key_v1`
**Describe the bug**
`ssh_file:encode` has an incorrect typespec for inputs when its second parameter is `openssh_key_v1`. It takes `experimental_openssh_key_v1()` for its first parameter which is, as of OTP 28.3:
```erl
[{key(), openssh_key_v1_attributes()}]
```
whereas the function actually takes, for its first parameter, as of OTP 28.3:
```erl
[{[keypair_with_comment()], openssh_key_v1_attributes()}]
when keypair_with_comment() :: {public_key:public_key(), public_key:private_key(), binary()}
                             | {public_key:private_key(), binary()}
```
where the binary is a comment

**Affected versions**
OTP 28.3

### PR DESCRIPTION
**Pull request by u3s**
- Fixes #10526

### CODE REVIEW

**Review by Mikaka27 — APPROVED** [review]

File: lib/ssh/src/ssh_message.erl [hunk 1]
```diff
@@ -687,23 +687,23 @@ ssh2_privkey_encode(#'DSAPrivateKey'
...
-                    {version = 1,
+                    {version = Version,
                      parameters = {namedCurve,OID},
                      privateKey = Priv,
-                     publicKey = Pub
-                    }) when OID == ?'id-Ed25519' orelse
-                            OID == ?'id-Ed448' ->
+                     publicKey = Pub})
+  when OID =:= ?'id-Ed25519' orelse OID =:= ?'id-Ed448',
+       Version =:= 1 orelse Version =:= ecPrivkeyVer1 -> % currently used atom and legacy value 1
```
Comment (IngelaAndin) [inline lib/ssh/src/ssh_message.erl]: Maybe reverse the test as probably ecPrivKeyVer1 will be the value in new systems and value 1 will be the backwards compatibility that should not happen that much.

File: lib/ssh/src/ssh_file.erl [hunk 2]
```diff
@@ -245,8 +245,14 @@ call that initiates an ssh connection.
 -doc(#{group => <<"Options">>}).
 -type key() :: public_key:public_key() | public_key:private_key() .
 -doc(#{group => <<"Options">>}).
--type experimental_openssh_key_v1() :: [{key(), openssh_key_v1_attributes()}].
--doc "Types for the experimental implementaition of the `openssh_key_v1` format.".
+-type experimental_openssh_key_v1_encode() ::
+        [{[{public_key:public_key(), public_key:private_key(), binary()} |
```
Comment (IngelaAndin) [inline lib/ssh/src/ssh_file.erl]: What is the binary() , maybe it should say Comment::binary()  ?

File: lib/ssh/src/ssh_message.erl (hunk 1 above)
Comment (u3s) [reply lib/ssh/src/ssh_message.erl]: fixed

File: lib/ssh/src/ssh_file.erl (hunk 2 above)
Comment (u3s) [reply lib/ssh/src/ssh_file.erl]: fixed
