### PR TITLE
ssl: Use unique identifier for CRL db

### LINKED ISSUE #8891: CRL cache key being the path part of the distribution endpoint leads to clash
**Describe the bug**

The CRL cache key is the extracted path part of a CRL DP URI.
https://github.com/erlang/otp/blob/f58748299f0d8ec90222deb621b16c138e256303/lib/ssl/src/ssl_crl_cache.erl#L155-L158

This leads to clash when two DPs share the same path.

**To Reproduce**

Test with two different client certificates, having the same CRL DP URI path.

**Expected behavior**

Work with multiple CRL DPs

**Affected versions**

ALL?

### PR DESCRIPTION
**Pull request by IngelaAndin**
Closes #8891

### CODE REVIEW

File: lib/ssl/src/ssl_crl_cache.erl [hunk 1]
```diff
@@ -143,8 +143,12 @@ delete({der, CRLs}) ->
 
 delete(URI) ->
     case uri_string:normalize(URI, [return_map]) of
-	#{scheme := "http", path := Path} ->
-	    ssl_manager:delete_crls(string:trim(Path, leading, "/"));
+	#{scheme := "http",
+          host := Host,
+          path := Path} = Map ->
+            Port = maps:get(port, Map, 80),
+            Key = Host ++ ":" ++ integer_to_list(Port) ++ Path,
```
Comment (u3s) [inline lib/ssl/src/ssl_crl_cache.erl:150]: maybe have a helper function wrapping
`Host ++ ":" ++ integer_to_list(Port) ++ Path`

so same procedure is always followed and it is harder to make a mistake by altering to few places ...

File: lib/ssl/test/ssl_crl_SUITE.erl [hunk 2]
```diff
@@ -576,18 +576,18 @@ delete_crl_with_path(Config) ->
...
     [_, _,_, _, Prop] = StatusInfo,
     State = ssl_test_lib:state(Prop),
+    #'DistributionPoint'{distributionPoint = {fullName, Names}} = DP,
+    {_, URI} = lists:keyfind(uniformResourceIdentifier, 1, Names),
     case element(5, State) of
         [_, _, _, {CRLCache, _}] ->
-            URI = "http://localhost/otpCA/crl.pem",
-            not_available = ssl_crl_cache:lookup(DP, issuer, {{CRLCache, unused}, unused}),
+            not_available = ssl_crl_cache:lookup(URI, issuer, {{CRLCache, unused}, unused}),
             ok = ssl_crl_cache:insert(URI, {der, CRLs}),
```
Comment (u3s) [inline lib/ssl/test/ssl_crl_SUITE.erl:587]: Maybe I'm missing something, but shouldn't we have some more testing? for example, for case of inserting CRLs sharing the same path and not crashing due to this PR?

Comment (u3s) [reply lib/ssl/test/ssl_crl_SUITE.erl:587]: We agreed to add test case in separate PR, later.

**Review by u3s — APPROVED** [review]

File: lib/ssl/test/ssl_crl_SUITE.erl (hunk 2 above)
Comment (IngelaAndin) [reply lib/ssl/test/ssl_crl_SUITE.erl:587]: I am sure you will nag me if I do not keep that promise  ;)
