### PR TITLE
public_key: Fix encoding and decoding extensions

### LINKED ISSUE #10404: public_key:der_encode fails at encoding 'InvalidityDate'
**Describe the bug**
`public_key:der_encode`supports `InvalidityDate` as ASN1 Extension Type but the underlying code in `pubkey_cert_records:encode_extensions` calls `PKIX1Implicit-2009':getenc_CertExtensions(Id)`

The issue seams to be that `InvalidityDate` is a CrlEntryExtension so `getenc_CertExtensions` does not support its ID.

Not even `getenc_CrlExtensions` does so, the only match for its ID I found it in `getenc_CrlEntryExtensions`

**To Reproduce**
Any shell on OTP 28.2
```
18> public_key:der_encode('InvalidityDate', "20220127000000Z").
** exception error: no case clause matching "20220127000000Z"
     in function  'PKIX1Implicit-2009':'-getenc_CertExtensions/1-fun-0-'/3 (../src/PKIX1Implicit-2009.erl:3128)
     in call from pubkey_cert_records:'-encode_extensions/1-fun-0-'/1 (pubkey_cert_records.erl:488)
     in call from lists:map/2 (lists.erl:2385)
     in call from public_key:der_encode/2 (public_key.erl:978)
```

**Expected behavior**
I would expect that all supported `Asn1ExtType` matched by the public API function are then supported by the internal libraries.

**Affected versions**
OTP 28.2

**Additional context**
I noticed this while searching a way to encode and decode ASN1 GeneralizedTime using the public_key API. I am posting this issue because it looks to me like a possible bug.

### PR DESCRIPTION
**Pull request by dgud**
Extensions was not looked up correctly they are split depending on extension structure, currently three different functions.

Clean up code in public_key to lookup the extensions before enc/decoding them so that all supported extensions will be available.

Also remove the type that where extensions and couldn't be called directly, SubjectAltName and FreshestCRL.

Test encode/decode all them.

Fixes #10404

### CODE REVIEW

File: lib/public_key/src/pubkey_cert_records.erl [hunk 1]
```diff
@@ -352,34 +352,59 @@ encode_supportedPublicKey(#'OTPSubjectPublicKeyInfo'{
...
+extension_id(?'id-ce-authorityKeyIdentifier') ->
+    {'PKIX1Implicit-2009', getdec_CrlExtensions, getenc_CrlExtensions, 'AuthorityKeyIdentifier'};
+extension_id(?'id-ce-subjectKeyIdentifier') ->
+    {'PKIX1Implicit-2009', getdec_CertExtensions, getenc_CertExtensions, 'SubjectKeyIdentifier'};
+extension_id(?'id-ce-keyUsage') ->
+    {'PKIX1Implicit-2009', getdec_CertExtensions, getenc_CertExtensions, 'KeyUsage'};
+extension_id(?'id-ce-privateKeyUsagePeriod') ->
+    {'PKIX1Implicit-2009', getdec_CertExtensions, getenc_CertExtensions, 'PrivateKeyUsagePeriod'};
+extension_id(?'id-ce-certificatePolicies') ->
+    {'PKIX1Implicit-2009', getdec_CertExtensions, getenc_CertExtensions, 'CertificatePolicies'};
```
Comment (IngelaAndin) [inline lib/public_key/src/pubkey_cert_records.erl:364]: Remove white space

File: lib/public_key/src/pubkey_cert_records.erl [hunk 2]
```diff
@@ -352,34 +352,59 @@ encode_supportedPublicKey(#'OTPSubjectPublicKeyInfo'{
...
+    {'PKIX1Implicit-2009', getdec_CertExtensions, getenc_CertExtensions, 'PolicyConstraints'};
+extension_id(?'id-ce-extKeyUsage') ->
+    {'PKIX1Implicit-2009', getdec_CertExtensions, getenc_CertExtensions, 'ExtKeyUsageSyntax'};
+extension_id(?'id-ce-inhibitAnyPolicy') ->
+    {'PKIX1Implicit-2009', getdec_CertExtensions, getenc_CertExtensions, 'InhibitAnyPolicy'};
+extension_id(?'id-ce-freshestCRL') ->
+    {'PKIX1Implicit-2009', getdec_CrlExtensions, getenc_CrlExtensions, 'FreshestCRL'};
+extension_id(?'id-ce-issuingDistributionPoint') ->
+    {'PKIX1Implicit-2009', getdec_CrlExtensions, getenc_CrlExtensions, 'IssuingDistributionPoint'};
 %% Missing in public_key doc
```
Comment (IngelaAndin) [inline lib/public_key/src/pubkey_cert_records.erl]: Remove comment these are documented

**Review by IngelaAndin — APPROVED** [review]
