### PR TITLE
ssl: validate CertificateVerify capability in certs_keys selection 

### LINKED ISSUE #10915: ssl: server selecting wrong certificate when multiple `cert_keys` are configured
**Describe the bug**
When a TLS 1.3 server is configured with multiple certificate/key pairs via `certs_keys`, the server may select a certificate whose public key type is incompatible with the client's `signature_algorithms` extension. This causes the handshake to fail with `insufficient_security` / `no_suitable_signature_algorithm` even though a suitable certificate exists in the server's configuration.

In my tests, this happened when I used two certs: one ECDSA and one RSA, both signed by the same RSA CA. When using a client that only accepts RSA, `ssl` prioritizes using ECDSA and then fails with:
```
TLS server: In state start at tls_handshake_1_3.erl:1505 generated SERVER ALERT: Fatal - Insufficient Security
      - no_suitable_signature_algorithm
```

**To Reproduce**

Have a server listening with multiple cert types:
```erlang
CertsKeys = [
  #{cert => ECDSACert, key => ECDSAKey},
  #{cert => RSACert,   key => RSAKey}
],
ServerOpts = [{certs_keys, CertsKeys}, {versions, ['tlsv1.3']}],
{ok, LSock} = ssl:listen(Port, ServerOpts).
```

Connect to it with restricted signature_algs:
```erlang
ClientOpts = [
  {verify, verify_peer},
  {cacerts, [RSACACert]},
  {versions, ['tlsv1.3']},
  {signature_algs, [rsa_pss_rsae_sha256]},
  {signature_algs_cert, [rsa_pkcs1_sha256, rsa_pss_rsae_sha256]}
],
{ok, Sock} = ssl:connect(Host, Port, ClientOpts).
```

[A script in this repository](https://github.com/v0idpwn/otp-cert-selection-bug-repro) does all the setup and compares the erlang server with `openssl_s`, which succeeds with the same client configuration. 

**Expected behavior**
Sucessfully handshake, like openssl_s.

**Affected versions**
At least 27.3 and main.

### PR DESCRIPTION
**Pull request by v0idpwn**
This adds a select_sign_algo check before committing to a cert/key pair in select_server_cert_key_pair/7. Previously, only the cert's signature was validated against the client's algorithms (check_cert_sign_algo), not whether the key could produce an acceptable CertificateVerify.

Closes #10915.

### CODE REVIEW

**Comment by v0idpwn** [comment]
Should I have targeted `maint`, since this is a fix?

**Comment by IngelaAndin** [comment]
@v0idpwn  Yes please target if for maint. Although we have no more planned maint-patch-release I will piggyback it on some none planned patch for OTP-28 track, once we are satisfied with it, that is bound to come.

File: lib/ssl/src/tls_server_connection_1_3.erl [hunk 1]
```diff
@@ -709,25 +709,37 @@ select_server_cert_key_pair(Session, [#{private_key := Key, certs := [Cert| _] =
                             #state{static_env = #static_env{cert_db = CertDbHandle,
                                                             cert_db_ref = CertDbRef}} = State,
                             Default0) ->
-    {_, SignAlgo, SignHash, _, _} = tls_handshake_1_3:get_certificate_params(Cert),
+    #{signature_algs := ServerSignAlgs} = State#state.ssl_options,
+    {PublicKeyAlgo, SignAlgo, SignHash, RSAKeySize, Curve} =
+        tls_handshake_1_3:get_certificate_params(Cert),
     %% TODO: We do validate the signature algorithm and signature hash
     %% but we could also check if the signing cert has a key on a
     %% curve supported by the client for ECDSA/EDDSA certs
```
Comment (v0idpwn) [inline lib/ssl/src/tls_server_connection_1_3.erl]:
```suggestion
```
Removing as it checks now

**Comment by v0idpwn** [comment]
Hm, after I changed the target from `master` to `maint` it started failing.

**Comment by IngelaAndin** [comment]
@v0idpwn I think this failure is  is unrelated and  test case timing issue. I have been testing your code locally and I think there is a small improvement that we can make . I will come back with more info tomorrow.

**Comment by IngelaAndin** [comment]
@v0idpwn  I took the liberty to squash your commits and base them on a release tag. I also added a commit to move 
the whole logic of selecting protocol signature into the select_server_cert_key_pair function to avoid having to run the  tls_handshake_1_3:check_cert_sign_algo twice.

**Comment by v0idpwn** [comment]
Looks great to me! The previous approach bothered me too, but I was trying to reduce the scope of my changes as much as possible :)
