### PR TITLE
ssl: Handle missing certificate_authorities extension

### LINKED ISSUE #5783: TLS handshake issue in OTP 24.3
**Describe the bug**
When attempting to connect to a remote server, I receive the following error:

```
[error] pid=<0.737.0> [error] GenStateMachine #PID<0.737.0> terminating
** (KeyError) key :certificate_authorities not found in: %{signature_algs: {:signature_algorithms, [:ecdsa_secp256r1_sha256, :ecdsa_secp384r1_sha384, :ecdsa_secp521r1_sha512, :eddsa_ed25519, :eddsa_ed448, :rsa_pss_pss_sha256, :rsa_pss_pss_sha384, :rsa_pss_pss_sha512, :rsa_pss_rsae_sha256, :rsa_pss_rsae_sha384, :rsa_pss_rsae_sha512, :rsa_pkcs1_sha256, :rsa_pkcs1_sha384, :rsa_pkcs1_sha512, {:sha224, :ecdsa}, {:sha224, :rsa}]}}
    :erlang.map_get(:certificate_authorities, %{signature_algs: {:signature_algorithms, [:ecdsa_secp256r1_sha256, :ecdsa_secp384r1_sha384, :ecdsa_secp521r1_sha512, :eddsa_ed25519, :eddsa_ed448, :rsa_pss_pss_sha256, :rsa_pss_pss_sha384, :rsa_pss_pss_sha512, :rsa_pss_rsae_sha256, :rsa_pss_rsae_sha384, :rsa_pss_rsae_sha512, :rsa_pkcs1_sha256, :rsa_pkcs1_sha384, :rsa_pkcs1_sha512, {:sha224, :ecdsa}, {:sha224, :rsa}]}})
    (ssl 10.7) tls_handshake_1_3.erl:1442: :tls_handshake_1_3.process_certificate_request/2
    (ssl 10.7) tls_handshake_1_3.erl:1094: :tls_handshake_1_3.do_wait_cert_cr/2
    (ssl 10.7) tls_connection_1_3.erl:410: :tls_connection_1_3.wait_cert_cr/3
    (stdlib 3.17.1) gen_statem.erl:1203: :gen_statem.loop_state_callback/11
    (ssl 10.7) tls_connection.erl:155: :tls_connection.init/1
    (stdlib 3.17.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

Full stack trace:
https://gist.github.com/acco/74f768da80b96775b14cf31889ecee8e

**To Reproduce**
Unfortunately it involves connecting to a private database, so I can't share reproducible steps. Trying to see if I can spin up a test db for the purposes of this ticket. This issue does not occur for every database I try to connect to, just a small subset of them.

If there's something I can run to determine details about remote server (TLS version etc) let me know.

**Expected behavior**
TLS connection established.

**Affected versions**
For me, this issue occurs in 24.3 but not 24.2.2.

**Additional context**
None.

### PR DESCRIPTION
**Pull request by IngelaAndin**
Closes #5783

### CODE REVIEW

File: lib/ssl/src/tls_handshake_1_3.erl [hunk 1]
```diff
@@ -1439,7 +1439,7 @@ process_certificate_request(#certificate_request_1_3{
                        maps:get(signature_algs, Extensions, undefined)),
     ServerSignAlgsCert = get_signature_scheme_list(
                            maps:get(signature_algs_cert, Extensions, undefined)),
-    CertAuths = get_certificate_authorites(maps:get(certificate_authorities, Extensions)),
+    CertAuths = get_certificate_authorites(maps:get(certificate_authorities, Extensions, undefined)),
```
Comment (IngelaAndin) [inline lib/ssl/src/tls_handshake_1_3.erl:1442]: Here we need the default value of undefined, this is more difficult to test as you need a server that does not send the extension in its certificate request message. I will add this issue as an additional reason to extend our test framework.
