### PR TITLE
public_key: Adjust certificate key usage compatible check

### LINKED ISSUE #9208: SSL problem with OTP 27.1.3
**Describe the bug**
On OTP 27.1.3 connection to an API endpoint stopped working, and it worked fine with OTP 26.

Not really sure where to start looking.

```
iex(22)> :ssl.connect('THE_SERVICE', 443, ssl_opts)
warning: single-quoted strings represent charlists. Use ~c"" if you indeed want a charlist or use "" instead
└─ iex:22:14

10:12:43.936 mfa=:ssl_handshake.path_validation_alert/3 [notice] TLS :client: In state :certify at ssl_handshake.erl:2199 generated CLIENT ALERT: Fatal - Unsupported Certificate
 - {:key_usage_mismatch,
 {{:Extension, {2, 5, 29, 15}, true, [:keyCertSign, :cRLSign]},
  {:Extension, {2, 5, 29, 37}, false,
   [{1, 3, 6, 1, 5, 5, 7, 3, 2}, {1, 3, 6, 1, 5, 5, 7, 3, 1}]}}}
{:error,
 {:tls_alert,
  {:unsupported_certificate,
   ~c"TLS client: In state certify at ssl_handshake.erl:2199 generated CLIENT ALERT: Fatal - Unsupported Certificate\n {key_usage_mismatch,{{'Extension',{2,5,29,15},true,[keyCertSign,cRLSign]},\n                      {'Extension',{2,5,29,37},\n                                   false,\n                                   [{1,3,6,1,5,5,7,3,2},\n                                    {1,3,6,1,5,5,7,3,1}]}}}"}}}
```

**Affected versions**
27.1.3

### PR DESCRIPTION
**Pull request by IngelaAndin**
Consider keyCertSign to compatible with extended key usage for TLS client/server auth in CAs

closes #9208

### CODE REVIEW

**Comment by IngelaAndin** [comment]
This is one possible solution, we are not sure it is the right one yet and we are investigating.

File: lib/public_key/src/pubkey_cert.erl [hunk 1]
```diff
@@ -1805,41 +1805,48 @@ compatible_ext_key_usage(undefined, _, endentity) -> %% keyusage (first arg )is
...
-        is_compatible_purposes(KeyUse, Rest);
-is_compatible_purposes(KeyUse, [?'id-kp-clientAuth'| Rest]) ->
+        is_compatible_purposes(KeyUse, Rest, Type);
+is_compatible_purposes(KeyUse, [?'id-kp-clientAuth'| Rest], ca = Type) ->
+    %% keyCertSign is already verified for a ca and considered compatible
+    is_compatible_purposes(KeyUse, Rest, Type);
+is_compatible_purposes(KeyUse, [?'id-kp-clientAuth'| Rest], endentity = Type) ->
     (lists:member(digitalSignature, KeyUse)
      orelse
        (lists:member(keyAgreement, KeyUse) orelse lists:member(keyEncipherment, KeyUse)))
```
Comment (u3s) [inline lib/public_key/src/pubkey_cert.erl:1831]: is it correct to have `keyEncipherment` for `id-kp-clientAuth` and not `id-kp-serverAuth` ?

```
         id-kp-serverAuth OBJECT IDENTIFIER ::= { id-kp 1 }
         -- TLS WWW server authentication
         -- Key usage bits that may be consistent: digitalSignature,
         -- **keyEncipherment** or keyAgreement
         id-kp-clientAuth OBJECT IDENTIFIER ::= { id-kp 2 }
         -- TLS WWW client authentication
         -- Key usage bits that may be consistent: digitalSignature
         -- and/or keyAgreement
```

Comment (u3s) [inline lib/public_key/src/pubkey_cert.erl:1831]: are parenthesis around this needed for any reason? simplify code?

`(lists:member(keyAgreement, KeyUse) orelse lists:member(keyEncipherment, KeyUse))`

File: lib/public_key/src/pubkey_cert.erl [hunk 2]
```diff
@@ -1805,41 +1805,48 @@ compatible_ext_key_usage(undefined, _, endentity) -> %% keyusage (first arg )is
...
+is_compatible_purposes(KeyUse, [?'id-kp-codeSigning'| Rest], Type) ->
     lists:member(digitalSignature, KeyUse) andalso
-        is_compatible_purposes(KeyUse, Rest);
-is_compatible_purposes(KeyUse, [?'id-kp-emailProtection'| Rest]) ->
+        is_compatible_purposes(KeyUse, Rest, Type);
+is_compatible_purposes(KeyUse, [?'id-kp-emailProtection'| Rest], Type) ->
     ((lists:member(digitalSignature, KeyUse) orelse
       lists:member(nonRepudiation, KeyUse))
      orelse
        (lists:member(keyAgreement, KeyUse) orelse lists:member(keyEncipherment, KeyUse)))
```
Comment (u3s) [inline lib/public_key/src/pubkey_cert.erl:1840]: are parenthesis around this needed for any reason? simplify code?
`(lists:member(keyAgreement, KeyUse) orelse lists:member(keyEncipherment, KeyUse))`

File: lib/public_key/src/pubkey_cert.erl [hunk 3]
```diff
@@ -1805,41 +1805,48 @@ compatible_ext_key_usage(undefined, _, endentity) -> %% keyusage (first arg )is
...
-        andalso is_compatible_purposes(KeyUse, Rest);
-is_compatible_purposes(KeyUse, [Id| Rest]) when Id == ?'id-kp-timeStamping';
-                                                Id == ?'id-kp-OCSPSigning'->
+        andalso is_compatible_purposes(KeyUse, Rest, Type);
+is_compatible_purposes(KeyUse, [Id| Rest],Type) when Id == ?'id-kp-timeStamping';
+                                                  Id == ?'id-kp-OCSPSigning'->
```
Comment (u3s) [inline lib/public_key/src/pubkey_cert.erl:1843]: wrong indentation

File: lib/public_key/src/pubkey_cert.erl [hunk 4]
```diff
@@ -1805,41 +1805,48 @@ compatible_ext_key_usage(undefined, _, endentity) -> %% keyusage (first arg )is
     true;
 compatible_ext_key_usage(_, undefined, _) ->
     true;
-compatible_ext_key_usage(#'Extension'{extnValue = KeyUse}, #'Extension'{extnValue = Purposes}, _) ->
+compatible_ext_key_usage(#'Extension'{extnValue = KeyUse}, #'Extension'{extnValue = Purposes}, Type) ->
```
Comment (u3s) [inline lib/public_key/src/pubkey_cert.erl:1808]: maybe improve the readability by having variable names in clause head more related to extension names.

- Purposes -> ExtKeyUse

(similarly to other places in module)

File: lib/public_key/src/pubkey_cert.erl [hunk 5]
```diff
@@ -1805,41 +1805,48 @@ compatible_ext_key_usage(undefined, _, endentity) -> %% keyusage (first arg )is
     true;
```
Comment (u3s) [inline lib/public_key/src/pubkey_cert.erl:1805]: line above
`compatible_ext_key_usage(undefined, _, endentity) -> %% keyusage (first arg )is mandantory in CAs`

- is confusing. what is the intention? is it after accepting end entity cert with no KeyUsage extension?
- why code comment refers to CAs if function head matches endentity?
- typo: mandantory -> mandatory

**Review by u3s — CHANGES_REQUESTED** [review]

File: lib/public_key/src/pubkey_cert.erl (hunk 1 above)
Comment (IngelaAndin) [reply lib/public_key/src/pubkey_cert.erl:1831]: Looks like client and server cases got switched good catch

File: lib/public_key/src/pubkey_cert.erl (hunk 5 above)
Comment (IngelaAndin) [reply lib/public_key/src/pubkey_cert.erl:1805]: I think the comment is from before the last argument was added, I can remove it.

File: lib/public_key/src/pubkey_cert.erl (hunk 4 above)
Comment (IngelaAndin) [reply lib/public_key/src/pubkey_cert.erl:1808]: I think it helps with having a good help function name that makes sense so  I added an assertion of the extesion-ids in the function clause  and made KeyUse -> KeyUses. I think it can help.

File: lib/public_key/src/pubkey_cert.erl (hunk 3 above)
Comment (IngelaAndin) [reply lib/public_key/src/pubkey_cert.erl:1843]: fixed

**Comment by IngelaAndin** [comment]
@u3s  Parenthesis I think it better captures the logic  (A orelse B) as a requirement for  current purpose and then andalso requirements for Rest (possible more purposes) are fullfilled.  Also A and B can be devided into sub logical expressions. Marking them with parenthesis makes them easier to follow I think.

File: lib/public_key/src/pubkey_cert.erl (hunk 1 above)
Comment (IngelaAndin) [reply lib/public_key/src/pubkey_cert.erl:1831]: See general comment in end of the PR.

File: lib/public_key/src/pubkey_cert.erl (hunk 2 above)
Comment (IngelaAndin) [reply lib/public_key/src/pubkey_cert.erl:1840]: See general comment in end of the PR.

File: lib/public_key/src/pubkey_cert.erl [hunk 6]
```diff
@@ -1864,8 +1874,8 @@ missing_basic_constraints(OtpCert, SelfSigned, ValidationState, VerifyFun, UserS
 	     UserState}
     end.
 
-is_valid_key_usage(KeyUse, Use) ->
-    lists:member(Use, KeyUse).
+is_valid_key_usage(KeyUses, Use) ->
```
Comment (u3s) [inline lib/public_key/src/pubkey_cert.erl:1877]: I'm not sure about value added by this function.
Also it is unfortunate it swaps the order of arguments. confusing and not optimal as I've read in some of Raimo comments.

**Review by u3s — DISMISSED** [review]

**Comment by IngelaAndin** [comment]
@u3s  As RFC is not using pure math-logic, I change the implementation a little using a few cases also so hopfully it is easier to read.

File: lib/public_key/src/pubkey_cert.erl (hunk 6 above)
Comment (IngelaAndin) [reply lib/public_key/src/pubkey_cert.erl:1889]: Ah , well lets remove it then.

**Review by u3s — DISMISSED** [review]

File: lib/public_key/src/pubkey_cert.erl [hunk 7]
```diff
@@ -1801,49 +1801,71 @@ is_digitally_sign_cert(Cert) ->
...
+     lists:member(nonRepudiation, KeyUses)) andalso
+        is_compatible_purposes(KeyUses, Rest, Type);
+is_compatible_purposes(KeyUses, [_| Rest], Type) -> %% Unknown purposes are for user verify_fun to care about
+    is_compatible_purposes(KeyUses, Rest, Type).
+
+
+ca_known_extend_key_use(ExtKeyUses) ->
     CAExtSet = ca_known_ext_key_usage(),
-    Intersertion = sets:intersection(CAExtSet, sets:from_list(ExtKeyUse)),
+    Intersertion = sets:intersection(CAExtSet, sets:from_list(ExtKeyUses)),
```
[the remark this answers is not in the document]
Comment (IngelaAndin) [reply lib/public_key/src/pubkey_cert.erl:1868]: Fixed

**Review by u3s — APPROVED** [review]
