### PR TITLE
erl_lint: Warn on remote-calling non-exported functions

### LINKED ISSUE #9092: Misleading unused function warning
**Describe the bug**

Running `erlc use_via_fun.erl`:

```
-module(use_via_fun).

-export([get_fun/0]).

get_fun() ->
  Fs = [fun use_via_fun:my_function/1],
  Fs.

% Used, but only via a remote function reference above
my_function(Y) -> Y.
```

Gives:

```
use_via_fun.erl:10:1: Warning: function my_function/1 is unused
%   10| my_function(Y) -> Y.
%     | ^
```

**Expected behavior**
No warning, since `my_function/1` is used via a function ref. Notably, we do _not_ get the warning if we reference it as a location function (i.e. as `fun my_function/1` vs. `fun use_via_fun:my_function/1`).

In this case, it's an issue because its temping to believe it is definitely safe to delete the "unused" function, but probably it should be exported instead?

**Affected versions**
OTP 26 & 27

### PR DESCRIPTION
**Pull request by jhogberg**
Fixes #9092

### CODE REVIEW

File: lib/stdlib/src/erl_lint.erl [hunk 1]
```diff
@@ -3023,6 +3031,17 @@ is_valid_call(Call) ->
         _ -> true
     end.
 
+%% Raises a warning if we're remote-calling an unexported function (or
+%% referencing it with `fun M:F/A`), as this is likely to be unintentional.
+check_unexported_function(Anno, M, F, A, #lint{module=M}=St) ->
+    case (is_warn_enabled(unexported_function, St) andalso
+          (not gb_sets:is_element({F, A}, exports(St)))) of
```
Comment (bjorng) [inline lib/stdlib/src/erl_lint.erl:3038]: Nitpick - I don't see any reason for the extra parentheses. In my opinion, they decrease readability. Also, it is a style-break from most of the other code in this module.

```suggestion
    case is_warn_enabled(unexported_function, St) andalso
          not gb_sets:is_element({F, A}, exports(St)) of
```

Comment (jhogberg) [reply lib/stdlib/src/erl_lint.erl]: When emacs-formatted, the `not` and the `true` are placed on the same line without the parentheses, so with multi-line case expressions I have the habit of wrapping them in parentheses. Other multi-line cases in the module (however not all) follow this pattern.

Thanks for pointing it out though, I had done it manually and forgotten that the `andalso` must also be on the next line for the formatter to be happy.

**Review by bjorng — APPROVED** [review]

**Review by bjorng — APPROVED** [review]
