### PR TITLE
Make alias analysis less conservative with calls

### LINKED ISSUE #8106: Missed private_append optimisation
**Describe the bug**
Given the following code:
```erlang
-module(test).

-export([test/2]).

test(X, Fun) ->
    test(X, Fun, <<>>),
    test2(X, Fun, <<>>).

test(X, Fun, Acc) ->
    Value = <<Acc/binary, X/binary>>,
    Fun(Value).

test2(X, _Fun, Acc) ->
    Value = <<Acc/binary, X/binary>>,
    id(Value).

id(X) -> X.
```

the compiler emits a `private_append` concatenation in `test2`, but an `append` concatenation in `test`.
In both cases all the theoretical cases for the optimisation to apply appear - the concatenation starts with an empty binary, and the value appended to is not re-used.

<details>
<summary>Compiler output</summary>

```
{function, test, 3, 344}.
  {label,343}.
    {func_info,{atom,test},{atom,test},3}.
  {label,344}.
    {'%',{var_info,{x,2},[{type,{t_bitstring,256,true}}]}}.
    {bs_create_bin,{f,0},
                   0,3,8,
                   {x,0},
                   {list,[{atom,append},
                          1,8,nil,
                          {tr,{x,2},{t_bitstring,256,true}},
                          {atom,all},
                          {atom,binary},
                          2,8,nil,
                          {x,0},
                          {atom,all}]}}.
    {'%',{var_info,{x,0},[{type,{t_bitstring,8,true}}]}}.
    {allocate,0,2}.
    {call_fun,1}.
    {deallocate,0}.
    return.


{function, test2, 3, 346}.
  {label,345}.
    {func_info,{atom,test},{atom,test2},3}.
  {label,346}.
    {'%',{var_info,{x,2},[{type,{t_bitstring,256,true}}]}}.
    {bs_create_bin,{f,0},
                   0,3,8,
                   {x,0},
                   {list,[{atom,private_append},
                          1,8,nil,
                          {tr,{x,2},{t_bitstring,256,true}},
                          {atom,all},
                          {atom,binary},
                          2,8,nil,
                          {x,0},
                          {atom,all}]}}.
    {'%',{var_info,{x,0},[{type,{t_bitstring,8,true}}]}}.
    {call_only,1,{f,67}}. % id/1
```

</details>

It seems that calling a fun somehow prevents the optimisation in a way that's not documented or expected.

**Expected behavior**

The compiler should emit a `private_append` concatenation in both cases.

**Affected versions**
Current master as of 78c143f948.

### PR DESCRIPTION
**Pull request by michalmuskala**
Even if we don't know anything about the callee, we can skip marking
arguments as aliased, if they are killed by the call - since we'll
never use them again. This allows the optimisation to apply in
many more cases.

Closes #8106

### CODE REVIEW

File: lib/compiler/src/beam_ssa_alias.erl [hunk 1]
```diff
@@ -831,17 +831,17 @@ aa_get_status_by_type(Type, StatusByType) ->
 aa_alias_surviving_args(Args, Call, SS, Anno, AAS) ->
     KillSet = aa_killset_for_instr(Call, AAS),
     ArgTypes = maps:get(arg_types, Anno, #{}),
-    aa_alias_surviving_args1(Args, 0, SS, ArgTypes, KillSet).
+    aa_alias_surviving_args1(Args, SS, ArgTypes, KillSet).
```
Comment (frej) [inline lib/compiler/src/beam_ssa_alias.erl:834]: Drop `ArgTypes` too, it's not used, and when that's done, we can drop `Anno` too. Then we can drop `Anno` from `aa_phi/5`...

Before the introduction of the new sharing state database, the index was used to look up argument types to avoid wholesale aliasing of tuples when extracted fields were given to a call. With the new representation this is harmless, and as we're no longer annotating all instructions which use `aa_alias_surviving_args` with types, we can just ignore the types and annotations.

**Review by frej — CHANGES_REQUESTED** [review]
That should do it, it's less conservative but I can't see any way in which it would be unsafe.

Apart from the comment about `aa_alias_surviving_args1()`, LGTM.

**Comment by frej** [comment]
BTW, add  `Closes #8106` to the commit message, to link the fix with the issue.

**Comment by michalmuskala** [comment]
I've used the suggestion to remove even more unused arguments - this was a nice cleanup!

**Comment by bjorng** [comment]
Thanks for your pull request.
