### PR TITLE
Fix crash when compiling is_list/1 call

### LINKED ISSUE #7504: [erlc] internal consistency check: uninitialized_reg
**Describe the bug**
Running erlc on the following:
```erlang
f([]) ->
    ok;
f(_V0) ->
    ((_V1 = erlang:is_list(_V0)) orelse binary_to_integer(list_to_bitstring([]))) / 0,
    _V1.
```
fails with
```
test493867:1: function f/1+16:
  Internal consistency check failed - please report this bug.
  Instruction: {call_ext,1,{extfunc,erlang,list_to_bitstring,1}}
  Error:       {uninitialized_reg,{y,0}}:
```

**Affected versions**
- master
- master + #7489 

**Additional context**
I could not reproduce this with an old version of OTP 25, so I suspect the bug was introduced in the last year.

### PR DESCRIPTION
**Pull request by bjorng**
Fixes #7504

### CODE REVIEW

File: lib/compiler/src/beam_ssa_codegen.erl [hunk 1]
```diff
@@ -1270,9 +1270,22 @@ cg_block([#cg_set{op=is_tagged_tuple,anno=Anno,dst=Bool,args=Args0}], {Bool,Fail
...
-    {[{test,is_nonempty_list,ensure_label(Fail, St),Args}],St};
+    case beam_args([Bool0|Args0], St) of
+        [{z,0}|Args] ->
+            {[{test,is_nonempty_list,Fail,Args}],St};
+        [Dst|Args] ->
+            %% This instruction was a call to is_list/1, which was
+            %% rewritten to an is_nonempty_list test by
+            %% beam_ssa_type. BEAM has no is_nonempty_list instruction
+            %% that will return a boolean, so we must revert it to an
+            %% is_list/1 call.
```
Comment (jhogberg) [inline lib/compiler/src/beam_ssa_codegen.erl:1284]: Given the relative rarity of needing boolean values from type tests, I wonder if it wouldn't be better to convert them at an early stage from `A = is_xyz(X)` to something like `A = if is_xyz(X) -> true; not is_xyz(X) -> false end` (it would also simplify some of the work I'm doing :smile:).

**Review by jhogberg — APPROVED** [review]
