### PR TITLE
SSL Fix DTSL issues

### LINKED ISSUE #7955: Dtls listen using inet and inet6 without {ip,ListenIP} override record in ets dtls_listener_sup
**Describe the bug**
When listen on same port using once inet and once inet6 without using {ip,ListenIP} will create one record in ets dtls_listener_sup

**To Reproduce**
1> application:ensure_all_started(ssl).
{ok,[crypto,asn1,public_key,ssl]}
2> spawn(fun() -> ssl:listen(0,[inet,{port,63450},{ciphers,[#{cipher => aes_256_gcm,key_exchange => psk,mac => aead,prf => sha384}]},{protocol,dtls},{versions,['dtlsv1.2']},{verify,verify_none},{psk_identity,"psk"}]) end).
3> spawn(fun() -> ssl:listen(0,[inet6,{ipv6_v6only,true},{port,63450},{ciphers,[#{cipher => aes_256_gcm,key_exchange => psk,mac => aead,prf => sha384}]},{protocol,dtls},{versions,['dtlsv1.2']},{verify,verify_none},{psk_identity,"psk"}]) end).

This gives in ets dtls_listener_sup
{{0,0,0,0},63450} {Pid1,Pid2}

**Expected behavior**
Except two records in ets dtls_listener_sup:
{{0,0,0,0},63450} {Pid1,Pid2} %inet
{{0,0,0,0,0,0,0,0},63450} {Pid3,Pid4} %inet6

**Affected versions**
Tested 25.x and 26.1.x

### PR DESCRIPTION
**Pull request by dgud**
Fix error and ipv6 handling.

Fixes #7955 and #7951

### CODE REVIEW

File: lib/ssl/src/dtls_socket.erl [hunk 1]
```diff
@@ -51,12 +51,16 @@ listen(Port, #config{inet_ssl = SockOpts,
                      ssl = SslOpts,
                      emulated = EmOpts,
                      inet_user = Options} = Config) ->
-    IP = proplists:get_value(ip, SockOpts, {0,0,0,0}),
+    DefIP = case proplists:get_value(inet6, SockOpts, false) of
+                false -> {0,0,0,0};
+                true -> {0,0,0,0, 0,0,0,0}
+            end,
```
Comment (u3s) [inline lib/ssl/src/dtls_socket.erl:57]: consider having `default_ip(SockOpts)` helper function, so DefIP variable is maybe not needed and we don't repeat code.

**Review by u3s — APPROVED** [review]

File: lib/ssl/test/dtls_api_SUITE.erl [hunk 2]
```diff
@@ -139,54 +142,64 @@ end_per_testcase(_TestCase, Config) ->
...
+                                        [_] = listener_and_ports(),
+                                        {error, _} = ssl:listen(Port, [{protocol, dtls} | ServerOpts])
+                               end),
     receive
-        {Pid, listened} ->
+        {'DOWN', Ref, _, Pid, _} ->
             ok
     end,
+
+    timer:sleep(200),  %% Async closing of port owner
```
Comment (IngelaAndin) [inline lib/ssl/test/dtls_api_SUITE.erl:163]: I have previously rewritten such test case to test the condition a few times (5-10) with a sleep between each try just to avoid tests that only fails sometimes but in the same time only sleeping just a little that will be enough in most cases.

**Review by IngelaAndin — APPROVED** [review]
Think the fix looks good, se comment on test cases.

**Review by u3s — APPROVED** [review]
