### PR TITLE
Reduce repeated work in concurrent code loading situations

### LINKED ISSUE #7479: OTP 26 -> meck issues with unloaded module
**Describe the bug**
In OTP 26.0.2 `meck:unload` is stuck at `code:delete(meck_util:original_name(Mod))`, we see `code_server` has a lot of messages related to `get_object_code` and some `load_module` for the same mecked module. Here the mecked module is called very often during `meck:unload`

**To Reproduce**

**Expected behavior**
In otp 25, we do not see any queued messages in code_server related to `get_object_code` or `load_module` for the same mecked module, and `code:delete` finishes instantly.

**Affected versions**
OTP 26. 

**Additional context**
- Sample messages
```
{code_call,&lt;0.64680.0&gt;,
                        {load_module,#Ref&lt;0.4109450702.1673396228.83575&gt;,
                            <some_module>,
                            "<path>/<some_module>.beam",
                            false,true}},
{code_call,&lt;0.67876.0&gt;,{get_object_code,<some_module>}},
{code_call,&lt;0.67878.0&gt;,{get_object_code,<some_module>}},
 ```

### PR DESCRIPTION
**Pull request by michalmuskala**
With changes in #6736 significant work when code loading was moved away from the code server and shifted into the requesting process. However, there could be a lot of repeated work, especially on system startup, if a lot of similar processes are started, all trying to load the same module at the same time, overwhelming the code server with `get_object_code` requests.

In this change, we add additional synchronisation to `ensure_loaded` that makes sure only one process at a time tries to load the module. In the added test showcasing the worst-case scenario of long load path and many concurrent requests, this changes the runtime (on my local machine) from 8s+ to around 200ms.

Furthermore, the special sync operation can be merged with this and save one round-trip to the code server.

Fixes #7479

### CODE REVIEW

**Comment by jhogberg** [comment]
This PR seems to cause crashes in `multi_load_SUITE:ensure_modules_loaded/1`, can you look into it?

```
*** System report during multi_load_SUITE:ensure_modules_loaded/1 2023-07-28 01:40:46.450 ***

=ERROR REPORT==== 28-Jul-2023::01:40:46.448231 ===
Error in process <0.50.0> on node test_server@idril with exit value:
{function_clause,
    [{code_server,try_finish_module,
         ["/ldisk/daily_build/26_opu_c_docker_72968.2023-07-27_21/test/test_server/ct_run.test_server@idril.2023-07-28_00.51.09/test.kernel_test.logs/run.2023-07-28_00.52.42/log_private/multi_load_ensure_modules_loaded/m__1_195074.beam",
          m__1_195074,#Ref<0.599638063.1805516801.41042>,true,<0.119740.0>,
          {state,<0.49.0>,"/daily_build/otp",
              [{"/ldisk/daily_build/26_opu_c_docker_72968.2023-07-27_21/test/test_server/ct_run.test_server@idril.2023-07-28_00.51.09/test.kernel_test.logs/run.2023-07-28_00.52.42/log_private/multi_load_ensure_modules_loaded",
                nocache},
               {"/ldisk/daily_build/26_opu_c_docker_72968.2023-07-27_21/test/test_server/ct_run.test_server@idril.2023-07-28_00.51.09/test.kernel_test.logs/run.2023-07-28_00.52.42/log_private",
                nocache},
               {"/ldisk/daily_build/26_opu_c_docker_72968.2023-07-27_21/test/kernel_test",
                nocache},
               {".",nocache},
               {"/daily_build/otp/lib/kernel-9.1/ebin",nocache},
               {"/daily_build/otp/lib/stdlib-5.0.3/ebin",nocache},
               {"/daily_build/otp/lib/sasl-4.2.1/ebin",nocache},
               {"/daily_build/proper/ebin",nocache},
               {"/daily_build/otp/lib/xmerl-1.3.31.1/ebin",nocache},
               {"/daily_build/otp/lib/wx-2.3/ebin",nocache},
               {"/daily_build/otp/lib/tools-3.6/ebin",nocache},
               {"/daily_build/otp/lib/tftp-1.1/ebin",nocache},
               {"/daily_build/otp/lib/syntax_tools-3.1/ebin",nocache},
               {"/daily_build/otp/lib/ssl-11.0.2/ebin",nocache},
               {"/daily_build/otp/lib/ssh-5.0.1/ebin",nocache},
               {"/daily_build/otp/lib/snmp-5.15/ebin",nocache},
               {"/daily_build/otp/lib/runtime_tools-2.0/ebin",nocache},
               {"/daily_build/otp/lib/reltool-1.0/ebin",nocache},
               {"/daily_build/otp/lib/public_key-1.14/ebin",nocache},
               {"/daily_build/otp/lib/parsetools-2.5/ebin",nocache},
               {"/daily_build/otp/lib/os_mon-2.9/ebin",nocache},
               {"/daily_build/otp/lib/odbc-2.14.1/ebin",nocache},
               {"/daily_build/otp/lib/observer-2.15/ebin",nocache},
               {"/daily_build/otp/lib/mnesia-4.22/ebin",nocache},
               {"/daily_build/otp/lib/megaco-4.5/ebin",nocache},
               {"/daily_build/otp/lib/jinterface-1.14/ebin",nocache},
               {"/daily_build/otp/lib/inets-9.0.2/ebin",nocache},
               {"/daily_build/otp/lib/ftp-1.2/ebin",nocache},
               {"/daily_build/otp/lib/eunit-2.8.2/ebin",nocache},
               {"/daily_build/otp/lib/et-1.7/ebin",nocache},
               {"/daily_build/otp/lib/erts-14.1/ebin",nocache},
               {"/daily_build/otp/lib/erl_interface-5.4/ebin",nocache},
               {"/daily_build/otp/lib/erl_docgen-1.5/ebin",nocache},
               {"/daily_build/otp/lib/eldap-1.2.11/ebin",nocache},
               {"/daily_build/otp/lib/edoc-1.2/ebin",nocache},
               {"/daily_build/otp/lib/diameter-2.3/ebin",nocache},
               {"/daily_build/otp/lib/dialyzer-5.1.1/ebin",nocache},
               {"/daily_build/otp/lib/debugger-5.3.2/ebin",nocache},
               {"/daily_build/otp/lib/crypto-5.3/ebin",nocache},
               {"/daily_build/otp/lib/compiler-8.3.3/ebin",nocache},
               {"/daily_build/otp/lib/common_test-1.25.1/ebin",nocache},
               {"/daily_build/otp/lib/asn1-5.1/ebin",nocache},
               {"/ldisk/daily_build/26_opu_c_docker_72968.2023-07-27_21/test/test_server",
                nocache},
               {"/ldisk/daily_build/26_opu_c_docker_72968.2023-07-27_21/test/kernel_test/application_SUITE_data/deadlock",
                nocache}],
              code_server,code_names,interactive,[],#{}}],
         [{file,"code_server.erl"},{line,1118}]},
     {code_server,loop,1,[{file,"code_server.erl"},{line,165}]}]}
```

**Comment by michalmuskala** [comment]
I'll take a look

File: lib/kernel/src/code_server.erl [hunk 1]
```diff
@@ -1180,6 +1188,62 @@ get_object_code(#state{path=Path} = St, Mod) when is_atom(Mod) ->
...
+                        case erlang:module_loaded(Mod) of
+                            true -> {reply, {module, Mod}, St};
+                            false -> {reply, {error, nofile}, St}
+                        end
+                end, Mod, From, St1)
+    end.
+
+monitor_loader(#state{loading = Loading0} = St, Mod, Pid, Bin, FName) ->
+    Tag = {'LOADER_DOWN', {Mod, Bin, FName}},
+    Ref = erlang:monitor(process, Pid, [{tag, Tag}]),
```
Comment (josevalim) [inline lib/kernel/src/code_server.erl:1212]: Very neat use of the tag to avoid the need for keeping stuff in state. Love it.

File: lib/kernel/src/code.erl [hunk 2]
```diff
@@ -187,10 +187,10 @@ ensure_loaded(Mod) when is_atom(Mod) ->
...
         true -> {module, Mod};
         false ->
-            case get_object_code(Mod) of
-                error -> call({sync_ensure_on_load, Mod});
-                {Mod,Binary,File} ->
-                    load_module(Mod, File, Binary, false, true)
+            case call({get_object_code_for_loading, Mod}) of
+                {module, Mod} -> {module, Mod};
+                {error, What} -> {error, What};
+                {Mod,Binary,File,Ref} -> load_module(Mod, File, Binary, false, Ref)
```
Comment (josevalim) [inline lib/kernel/src/code.erl:193]: I think we can still keep the `get_object_code` in this process and not in the code server, something like:

```suggestion
            case call({lock_for_loading, Mod}) of
                {module, Mod} -> {module, Mod};
                {error, What} -> {error, What};
                {go,Ref} ->
                  case get_object_code(Mod) of
                    :error -> call({no_module_to_load, Mod, Ref});
                    {Mod, Binary, File} -> load_module(Mod, File, Binary, false, Ref)
                  end
```

This should be the best of both worlds because we keep the work on the server minimal while avoiding concurrent work?

Comment (josevalim) [reply lib/kernel/src/code.erl:193]: Ignore me, the get object code needs to happen on the server. :)

**Comment by michalmuskala** [comment]
Sorry for the delay, I got a bit sick.

I've sent an update that should fix the `multi_load_SUITE`. This keeps the old behaviour for `ensure_modules_loaded`. I initially tried to add the locking mechanism there too, but due to the intermediate processes in `do_par` the logic was becoming quite unwieldy. So I limited the bug fix to just `ensure_loaded` since that's the function called implicitly by the error handler, and the main one causing issues.

**Comment by jhogberg** [comment]
Thanks, I've added it back to our tests :)

**Comment by michalmuskala** [comment]
Any updates on the results of the latest tests?

**Comment by frazze-jobb** [comment]
The tests looks good!
