### PR TITLE
Michal/diameter/fix-inheriting-of-indirect-inherits/otp-19626

### LINKED ISSUE #8235: Diameter .dia not automatically inheriting indirect inherits
**Describe the bug**

TS 29.273 SAR contains MIP6-Agent-Info AVP from RFC5447, which in turn contains MIP-Home-Agent-Address  AVP from RFC 4004.

In summary, specs A, B, C, where C depends on B, and B depends on A.

- Create a "diameter_3gpp_ts29_273_swx.dia" file containing SAR message definition and which inherits ("@inherits diameter_rfc5447", diameter_rfc5447.dia) to reference "MIP6-Agent-Info".
- Create a "diameter_rfc5447.dia" file containing MIP6-Agent-Info definition and which inherits ("@inherits diameter_rfc4004", diameter_rfc4004.dia) to reference "MIP-Home-Agent-Address".
- Create a "diameter_rfc4004.dia" file containing MIP-Home-Agent-Address definition.

Hence, diameter_3gpp_ts29_273_swx.dia is not directly inheriting RFC4004: no "@inherits diameter_rfc4004" in diameter_3gpp_ts29_273_swx.dia.

Then create some code which generates a SAR message containing MIP6-Agent-Info which in turn contains a MIP-Home-Agent-Address, and transmits it with diameter:call().
The diameter app will compile just fine, but it will fail to encode it, because the generated diameter_3gpp_ts29_273_swx.erl/hrl file lacks the code to encode MIP-Home-Agent-Address :
`[error] <0.164.0>@aaa_diameter_swx:handle_call:{175,13} Error: encode`

If one adds the explicit "@inherits diameter_rfc4004" in diameter_3gpp_ts29_273_swx.dia, then one can see that extra code is generated in diameter_3gpp_ts29_273_swx.erl/hrl and encoding works fine.

So, right now, one must inherit explicitly all indirect dependency .dia files in order to get a working encoder/decoder.

**To Reproduce**

The steps mentioned above can be seen in this branch "pespin/diameter-bug" I created in osmo-epdg.git:
https://gitea.osmocom.org/erlang/osmo-epdg/commits/branch/pespin/diameter-bug
One can see 3 commits in that branch:

- [Import generated code with bug](https://gitea.osmocom.org/erlang/osmo-epdg/commit/67555a7cc4f03da280098c6d2f4d381280e2f862): In there I simply import the generated code with the bug present (no explicit inherit of the indirect dependency rfc4004b in swx file).
- [diameter_3gpp_ts29_273_swx.dia: Fix missing dependency RFC4004](https://gitea.osmocom.org/erlang/osmo-epdg/commit/84b3ffafb0ed29d6c909209be6af203909657107): In here I apply the indirect dependency rfc4004 in diameter_3gpp_ts29_273_swx.dia.
- [Extra generated code after adding indirect dependency](https://gitea.osmocom.org/erlang/osmo-epdg/commit/b147f4f19aaade1634d9182853a6d1de31ee72cf): In here I commit the differences of the output .erl/.hrl after regenerating the code once the indirect dependency was applied.

By looking at the last commit one can see code which imho should have already been there already before inheriting the indirect spec.

**Expected behavior**

I see 2 solutions to the problem:
- Support automatically inheriting indirect dependencies. If there's spec "A, B and C;  C inherits B;  B inherits A", then when C inherits B, it should recursively generate code from A too.
- *Not* support automatically inheriting indirect dependencies, but at least fail at compile time saying there's a missing inherit/type, since clearly the generated code will fail at runtime.

**Affected versions**

I'm seeing this with erlang OTP 26.2.2-1 package from Archlinux.

**Additional context**

### PR DESCRIPTION
**Pull request by Mikaka27**
Fixes #8235

### CODE REVIEW

File: lib/diameter/test/diameter_indirect_inherits_SUITE.erl [hunk 1]
```diff
@@ -0,0 +1,933 @@
...
+        lists:join(" ]\n  [ ", OtherAvps) ++
+        " ]\n* [ AVP ]\n"
+    end, GroupedAvps).
+
+%% ===========================================================================
+
+verify_multiple_limited_imports_same_file(_) ->
+    %% This test checks that when you inherit same avp twice you get avp_already_defined error.
+    DictA = ?AVP_DICT_A,
+    DictB = ?AVP_DICT_B(["@inherits diameter_test_a AAA", "@inherits diameter_test_a AAA"]),
```
[the remark this answers is not in the document]
Comment (Mikaka27) [reply lib/diameter/test/diameter_indirect_inherits_SUITE.erl:473]: This tests specific error case and needs duplicated @inherits statement.

**Comment by lynxis** [comment]
So far I understand, you're fixing here a different thing, which could also fix this issue. 
Let have the following example:

C.dia inherits B, defined Grouped Cesa which uses the Grouped Beta from B.dia in an own group.
But the Grouped Beta uses the AVP alpha from A.dia. B.dia inherits A.

## c.dia
```
@inherits b
@vendor 10415 3GPP

@avp_types
   Cesa         1451    Grouped     MV

@grouped

Cesa ::= <AVP Header: 1451 10415>
   [ Beta ]
```

## b.dia
```
@inherits a
@vendor 10415 3GPP
@avp_types
    Beta         1551    Grouped     MV

@grouped 
Beta ::= <AVP Header: 1551 10415>
   [ Alpha ]
```

## a.dia
```
@vendor 10415 3GPP
@avp_types
    Alpha         1651    Unsigned32     MV
```


[a.dia.txt](https://github.com/user-attachments/files/22122528/a.dia.txt)
[b.dia.txt](https://github.com/user-attachments/files/22122529/b.dia.txt)
[c.dia.txt](https://github.com/user-attachments/files/22122530/c.dia.txt)

IMHO: the inherits are correctly assigned. C only reference to types of B and isn't using any A type. But B is using it.
EDIT: What I mean is, that this example of a.dia/... shouldn't need the new flag indirect-inherits, even for other cases it might be a good flag to use.

**Comment by pespin** [comment]
@Mikaka27 @lynxis with the reported testcase above, I can show how indeed it showcases a bug in my current Archlinux OTP (28.0.2-1). See how extra AVPs are added to the generated code when "@inherits a" is added explicitly to c.dia:


```diff
$ git diff --cached
diff --git a/dia/c.dia b/dia/c.dia
index 4dde94e..0bed9d3 100644
--- a/dia/c.dia
+++ b/dia/c.dia
@@ -1,3 +1,4 @@
+@inherits a
 @inherits b
 @vendor 10415 3GPP

diff --git a/src/c.erl b/src/c.erl
index 2f63113..f08c645 100644
--- a/src/c.erl
+++ b/src/c.erl
@@ -64,6 +64,7 @@ name2rec('Beta') -> 'Beta';
 name2rec(T) -> msg2rec(T).

 avp_name(1451, 10415) -> {'Cesa', 'Grouped'};
+avp_name(1651, 10415) -> {'Alpha', 'Unsigned32'};
 avp_name(1551, 10415) -> {'Beta', 'Grouped'};
 avp_name(_, _) -> 'AVP'.

@@ -76,11 +77,14 @@ avp_arity('Beta', 'Alpha') -> {0, 1};
 avp_arity(_, _) -> 0.

 avp_header('Cesa') -> {1451, 192, 10415};
+avp_header('Alpha') -> a:avp_header('Alpha');
 avp_header('Beta') -> b:avp_header('Beta');
 avp_header(_) -> erlang:error(badarg).

 avp(T, Data, 'Cesa', Opts) ->
     grouped_avp(T, 'Cesa', Data, Opts);
+avp(T, Data, 'Alpha', Opts) ->
+    avp(T, Data, 'Alpha', Opts, a);
 avp(T, Data, 'Beta', Opts) ->
     grouped_avp(T, 'Beta', Data, Opts);
 avp(_, _, _, _) -> erlang:error(badarg).
@@ -101,11 +105,13 @@ dict() ->
      {define, []},
      {enum, []},
      {grouped, [{"Cesa", 1451, [10415], [["Beta"]]}]},
-     {import_avps, [{b, [{"Beta", 1551, "Grouped", "MV"}]}]},
+     {import_avps,
+      [{a, [{"Alpha", 1651, "Unsigned32", "MV"}]},
+       {b, [{"Beta", 1551, "Grouped", "MV"}]}]},
      {import_enums, []},
      {import_groups,
       [{b, [{"Beta", 1551, [10415], [["Alpha"]]}]}]},
-     {inherits, [{"b", []}]},
+     {inherits, [{"b", []}, {"a", []}]},
      {messages, []},
      {vendor, {10415, "3GPP"}}].
```

**Comment by pespin** [comment]
@Mikaka27 I tried the same a,b,c testcase under rebar3 using OTP built out of this PR and I get the exact same result, so this PR is imho not fixing the problem.

**Comment by Mikaka27** [comment]
> @Mikaka27 I tried the same a,b,c testcase under rebar3 using OTP built out of this PR and I get the exact same result, so this PR is imho not fixing the problem.

Hi, could you share the test case along with commands you used where it doesn't work as you expect? Thanks :)

**Comment by pespin** [comment]
@Mikaka27 see https://github.com/erlang/otp/issues/8235#issuecomment-3250524414 , my fault due to not passing indirect_inherits, the PR is fine!

**Comment by Mikaka27** [comment]
> So far I understand, you're fixing here a different thing, which could also fix this issue. Let have the following example:
> 
> C.dia inherits B, defined Grouped Cesa which uses the Grouped Beta from B.dia in an own group. But the Grouped Beta uses the AVP alpha from A.dia. B.dia inherits A.
> ## c.dia
> 
> ```
> @inherits b
> @vendor 10415 3GPP
> 
> @avp_types
>    Cesa         1451    Grouped     MV
> 
> @grouped
> 
> Cesa ::= <AVP Header: 1451 10415>
>    [ Beta ]
> ```
> 
> ## b.dia
> 
> ```
> @inherits a
> @vendor 10415 3GPP
> @avp_types
>     Beta         1551    Grouped     MV
> 
> @grouped 
> Beta ::= <AVP Header: 1551 10415>
>    [ Alpha ]
> ```
> 
> ## a.dia
> 
> ```
> @vendor 10415 3GPP
> @avp_types
>     Alpha         1651    Unsigned32     MV
> ```
> 
> [a.dia.txt](https://github.com/user-attachments/files/22122528/a.dia.txt) [b.dia.txt](https://github.com/user-attachments/files/22122529/b.dia.txt) [c.dia.txt](https://github.com/user-attachments/files/22122530/c.dia.txt)
> 
> IMHO: the inherits are correctly assigned. C only reference to types of B and isn't using any A type. But B is using it. EDIT: What I mean is, that this example of a.dia/... shouldn't need the new flag indirect-inherits, even for other cases it might be a good flag to use.

Hi, is that a different problem you're having, other then @pespin or is that also resolved when using the indirect-inherits option?

File: lib/diameter/src/compiler/diameter_dict_util.erl [hunk 2]
```diff
@@ -1281,6 +1313,94 @@ dict(Mod) ->
...
+                    end, Inherits).
+
+%% enums_and_avps_from_modules/1
+%% Returns a list of {Mod, Enums, Avps} from modules
+enums_and_avps_from_modules(Mods) ->
+    lists:map(fun(Mod) ->
+                      Enums = enums_from_module(Mod),
+                      Avps = imported_avps_from_module(Mod),
+                      {Mod, Enums, Avps}
+              end, Mods).
```
Comment (bmk) [inline lib/diameter/src/compiler/diameter_dict_util.erl]: This looks like a list comprehension, or am I missing something?
[{Mod,enums_from_module(Mod),imported_avps_from_module(Mod)} || Mod <- Mods].
Of course, not sure that it actually improves readability in this case ;)

Comment (Mikaka27) [reply lib/diameter/src/compiler/diameter_dict_util.erl]: Yes you're right :) I can change that, and also at least in those 2 places as well:
https://github.com/Mikaka27/otp/blob/michal/diameter/fix-inheriting-of-indirect-inherits/otp-19626/lib/diameter/src/compiler/diameter_dict_util.erl#L1520-L1522
https://github.com/Mikaka27/otp/blob/michal/diameter/fix-inheriting-of-indirect-inherits/otp-19626/lib/diameter/src/compiler/diameter_dict_util.erl#L1531

File: lib/diameter/test/diameter_indirect_inherits_SUITE.erl [hunk 3]
```diff
@@ -0,0 +1,944 @@
...
+
+
+%% ===========================================================================
+
+-define(base, "base_rfc3588.dia").
+-define(S, atom_to_list).
+-define(L, integer_to_list).
+
+-define(CL(F),    ?CL(F, [])).
+-define(CL(F, A), ?LOG("DCOMP", F, A)).
```
Comment (bmk) [inline lib/diameter/test/diameter_indirect_inherits_SUITE.erl]: "DCOMP" should be "DII" I think.

File: lib/diameter/src/compiler/diameter_dict_util.erl (hunk 2 above)
Comment (Mikaka27) [reply lib/diameter/src/compiler/diameter_dict_util.erl]: Fixed

File: lib/diameter/test/diameter_indirect_inherits_SUITE.erl (hunk 3 above)
Comment (Mikaka27) [reply lib/diameter/test/diameter_indirect_inherits_SUITE.erl]: Fixed
