### PR TITLE
ssl: Correct connection state handling in TLS sender

### LINKED ISSUE #10191: TLS client's `max_fragment_length` is not respected by `tls_sender`
**Describe the bug**

Tested with tlsv1.2, with `{max_fragment_length, 1024}`

I can see in `ssl_gen_statem:prepare_connection_state` return value:

```
...
connection_states = #{max_fragment_length => 1024,
                                       current_read => ....
```

But the `connection_states` map used by `tls_sender` process when calling `tls_record:encode_data` does not have `max_fragment_length`.

I think the `reinit` callback should pass `max_fragment_length` to the sender process.

https://github.com/erlang/otp/blob/96bef0db7e48c8c1d626894e503599322023723a/lib/ssl/src/tls_gen_connection.erl#L206-L212

maybe like this:

```
  reinit(#state{protocol_specific = #{sender := Sender},
                connection_env = #connection_env{negotiated_version = Version},
                connection_states = #{current_write := Write} = CS} = State0) ->
      MaxFragmentLength = maps:get(max_fragment_length, CS, ?MAX_PADDING_LENGTH),
      tls_sender:update_connection_state(Sender, Write, Version, MaxFragmentLength),
      State = reinit_handshake_data(State0),
      garbage_collect(),
      State.

```

**To Reproduce**
 
- Use any TLS client that sends the `max_fragment_length` extension with value `1024`, (or `max_frag_enum=2`) in its ClientHello.
- Connect to an Erlang TLS server (OTP 27, TLS 1.2).
- Observe that the server’s `connection_states` initially includes `#{max_fragment_length => 1024, ...}` after handshake.
- However, in the `tls_sender` process, the `connection_states` map does not have this field.
- As a result, when `tls_record:encode_data/3` is called, it falls back to the default `?MAX_PLAIN_TEXT_LENGTH` (16 KB).
- The Erlang client may tolerate this, but many embedded clients (with small TLS record buffers) will fail with alerts such as "Bad Record MAC".

Although it's client to send the alert first (according to wireshark), the server does log this error too. e.g: 
`{tls_alert,{bad_record_mac,"TLS server: In state connection at ssl_record.erl:394 generated SERVER ALERT: Fatal - Bad Record MAC\n decryption_failed"}}`

**Expected behavior**

Server should respect the negotiated `max_fragment_length`.

**Affected versions**

27 (maybe earlier versions too)

### PR DESCRIPTION
**Pull request by IngelaAndin**
Optimization commit 28f7e80233718f9f42fe8863370f7e99ee14d22c broke max_fragment_length handling, that is the TLS sender lost its knowledge of the maximum fragment length.

Make TLS sender process aware of it in the cases it is negotiated, for default maximum we do not need to store it in the connection state.

Closes #10191

### CODE REVIEW

File: lib/ssl/src/tls_sender.erl [hunk 1]
```diff
@@ -341,11 +345,21 @@ connection(cast, #alert{} = Alert,  #data{buff = Buff} = StateData0) ->
...
            #data{connection_states = ConnectionStates, env = Env} = StateData) ->
-    CW = maps:remove(aead_handle, WritesState),
     hibernate_after(connection,
-                    StateData#data{connection_states = ConnectionStates#{current_write => CW},
-                                   env = Env#env{negotiated_version = Version}}, []);
-%%
+                    StateData#data{connection_states =
+                                       maps:without([max_fragment_length],
+                                                    ConnectionStates#{current_write => 
+                                                                          maps:remove(aead_handle, WritesState)}),
```
Comment (dgud) [inline lib/ssl/src/tls_sender.erl]: Nitpick move this to a variable, so we don't need a lot of newlines everywhere.

File: lib/ssl/src/tls_sender.erl [hunk 2]
```diff
@@ -170,12 +170,16 @@ peer_renegotiate(Pid) ->
...
+                              MaxFragLen :: tls_record:tls_max_frag_len()) -> ok.
 %% Description: So TLS connection process can synchronize the 
 %% encryption state to be used when sending application data. 
 %%--------------------------------------------------------------------
-update_connection_state(Pid, NewState, Version) ->
-    gen_statem:cast(Pid, {new_write, NewState, Version}).
+update_connection_state(Pid, NewState, Version, undefined) ->
+    gen_statem:cast(Pid, {new_write, NewState, Version});
+update_connection_state(Pid, NewState, Version, MaxFragLen) ->
+    gen_statem:cast(Pid, {new_write, NewState, Version, MaxFragLen}).
```
Comment (dgud) [inline lib/ssl/src/tls_sender.erl]: Why match here? 
IMO it would be better to do make a 
`case MaxFragLen of undefined ->` 
in `connection` and in `handshake`.

To avoid code duplication, i.e. two clauses that does almost the same thing.

File: lib/ssl/src/tls_sender.erl [hunk 3]
```diff
@@ -427,7 +441,26 @@ handshake(cast, {new_write, WriteState0, Version},
     {next_state, connection,
      StateData#data{connection_states = ConnectionStates,
```
Comment (dgud) [inline lib/ssl/src/tls_sender.erl]: You missed removing the `max_fragment_length` in the clause above.
As you did in the connection state above.

File: lib/ssl/src/tls_sender.erl (hunk 1 above)
Comment (IngelaAndin) [reply lib/ssl/src/tls_sender.erl]: This particular code is removed now.

File: lib/ssl/src/tls_sender.erl (hunk 2 above)
Comment (IngelaAndin) [reply lib/ssl/src/tls_sender.erl]: Good point I think I was differentiating between the case to still keep the state as small as possible in the wrong place.
See new solution.

File: lib/ssl/src/tls_sender.erl (hunk 3 above)
Comment (IngelaAndin) [reply lib/ssl/src/tls_sender.erl]: Should also be solved by new solution

**Review by dgud — APPROVED** [review]
Nice.

**Review by dgud — APPROVED** [review]

**Comment by zmstone** [comment]
Thanks for the fix. Since this PR is fixing a regression that was introduced during an optimization, could you please add a test case that covers this scenario?

Without a regression test, we risk the same issue creeping back in the future when performance-related changes are made again. A targeted test would both validate this fix and serve as protection against similar regressions.

**Comment by IngelaAndin** [comment]
Yes we will be adding a regression test. We are working on some property based tests where this is easy to test, this is not ready for production yet.  It could be possible with an awkward white-box test but we will put our efforts into the property based test instead, so it is coming.
