### PR TITLE
Skip beam_ssa_alias for modules with huge functions

### LINKED ISSUE #7667: OTP 26.1 get stuck when compiling gun
**Describe the bug**

When trying to compile gun (https://github.com/ninenines/gun) under OTP 26.1, the compiler never finishes.

**To Reproduce**

with OTP-26.1 installed from kerl:
```
git clone https://github.com/ninenines/gun
cd gun
rebar3 compile
```

I have been able to narrow the problem down to `src/gun_public_suffix.erl`, e.g.:

```
gun$ erl
Erlang/OTP 26 [erts-14.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]

Eshell V14.1 (press Ctrl+G to abort, type help(). for help)
1> c("src/gun_public_suffix.erl").

 .... not response and 100% CPU load ....
```

**Expected behavior**

compilation finishes

**Affected versions**

OTP-26.1

**Additional context**

OS: Ubuntu 23.10
rebar3: 3.22.0
OTP-26.1 compiled from source with kerl, no special options

### PR DESCRIPTION
**Pull request by bjorng**
The implementation of the `beam_ssa_alias` pass in OTP 26 can become extremly slow for modules containing huge functions. The `master` branch (for the OTP 27 release next year) already contains a much better implementation that handles huge functions. That implementation is also very different, so we don't want to back-port it to OTP 26.

To make the compiler in OTP 26 usable for huge functions, add a heuristic that disables the alias analysis pass for functions exceeding a certain number of blocks.

Fixes #7667

### CODE REVIEW

File: lib/compiler/src/beam_ssa_alias.erl [hunk 1]
```diff
@@ -127,14 +127,33 @@
...
+
+%%%
+%%% Predicate to check whether there any huge functions in this
+%%% compilation unit.
+%%%
+
+-spec any_huge_function(st_map()) -> boolean().
+
+any_huge_function(StMap) ->
+    lists:any(fun(#opt_st{ssa=Code}) ->
```
Comment (jhogberg) [inline lib/compiler/src/beam_ssa_alias.erl:154]: Nitpick: import `any/2` as per our convention?

**Review by jhogberg — APPROVED** [review]
LGTM
