### PR TITLE
Restore broken optimization of unicode conversion function

### LINKED ISSUE #10072: Whether unicode:bin_is_7bit/1 exist bug?
**Describe the bug**
This function essentially checks whether a binary string consists entirely of ASCII characters from 0 to 127. I'm not sure if my understanding is wrong, but I can't find any test examples that return true for this function. I even tried the latest OTP28, and the result was the same.

**To Reproduce**
```shell
iex(13)> :unicode.bin_is_7bit(<<1, 2, 3>>)
false
iex(14)> :unicode.bin_is_7bit(<<"Hello, World!">>)
false
```

**Expected behavior**
Hopefully this function works as expected.

**Affected versions**
OTP27、 OTP28

**Additional context**
By looking at the source code, I found the following suspicious places
```c
// erl_unicode.c
BIF_RETTYPE unicode_bin_is_7bit_1(BIF_ALIST_1)
{
    Sint need;
    if(!is_bitstring(BIF_ARG_1)) {
	BIF_RET(am_false);
    }
    need = latin1_binary_need(BIF_ARG_1);
    //  The aligned_binary_size function returns the number of bits, and need represents the number of bytes. The two are of different magnitudes, so this if conditional branch will never be true.
    if(need >= 0 && aligned_binary_size(BIF_ARG_1) == need) {
	BIF_RET(am_true);
    }
    BIF_RET(am_false);
}

static Sint aligned_binary_size(Eterm binary)
{
    Uint size = bitstring_size(binary);

    if (TAIL_BITS(size) == 0 && size <= ERTS_SINT_MAX) {
        return (Sint)size;
    }

    return -1;
}

static Sint latin1_binary_need(Eterm binary)
{
    const byte *temp_alloc = NULL, *bytes;
    Uint size;
    Sint need;
    Sint i;

    bytes = erts_get_aligned_binary_bytes(binary, &size, &temp_alloc);
    if (bytes == NULL) {
        return -1;
    }

    for(i = 0, need = 0; i < size; ++i) {
        if (bytes[i] & ((byte) 0x80)) {
            need += 2;
        } else {
            need += 1;
        }
    }

    erts_free_aligned_binary_bytes(temp_alloc);
    return need;
}
```

### PR DESCRIPTION
**Pull request by bjorng**
When used to convert from `latin1` to `utf8` or vice versa, the `unicode:characters_to_binary/3` function would return the original binary unchanged if it only contained 7-bit ASCII characters. For example:

    unicode:characters_to_binary("abc", latin1, utf8)

To determine whether the input was a binary with only 7-bit characters, the undocument BIF `unicode:bin_is_7bit/1` is used.

In Erlang/OTP 27, this optimization broke because `bin_is_7bit/1` accidentally started to always return `false`.

Resolves #10072

### CODE REVIEW

**Review by dgud — DISMISSED** [review]

File: erts/emulator/beam/erl_unicode.c [hunk 1]
```diff
@@ -885,15 +885,29 @@ static BIF_RETTYPE characters_to_utf8_trap(BIF_ALIST_4)
 
 BIF_RETTYPE unicode_bin_is_7bit_1(BIF_ALIST_1)
 {
-    Sint need;
-    if(!is_bitstring(BIF_ARG_1)) {
+    const byte *temp_alloc = NULL, *bytes;
+    Uint size;
+    Eterm ret;
+
+    if (!is_bitstring(BIF_ARG_1)) {
```
Comment (sverker) [inline erts/emulator/beam/erl_unicode.c]: You can skip the is_bitstring test as erts_get_aligned_binary_bytes does that (again).

**Review by sverker — DISMISSED** [review]

**Comment by michalmuskala** [comment]
As a further optimisation, I wonder if it would make sense to change that function to return `true | integer()` with an offset of the first non-7bit character this function found, so that the following conversion doesn't need to re-check the same prefix again.
Though that would probably go into master, rather than maint.

**Comment by bjorng** [comment]
> As a further optimisation, I wonder if it would make sense to change that function to return `true | integer()` with an offset of the first non-7bit character this function found, so that the following conversion doesn't need to re-check the same prefix again.

Is binary with a long prefix of 7-bit characters followed by some UTF-8 characters a common use case that is worth trying to optimize for?

> Though that would probably go into master, rather than maint.

Yes, definitely master **if** we are to do it.

**Comment by michalmuskala** [comment]
> Is binary with a long prefix of 7-bit characters followed by some UTF-8 characters a common use case that is worth trying to optimize for?

That's a good question, and I don't have a clear answer. I guess a classic example would be some sort of HTML document where usually the entire `<head>` tag would be ASCII, or some sort of JSON document with just a single full unicode value. Is it worth optimising for that? That's hard to answer.

**Review by dgud — APPROVED** [review]

**Review by sverker — APPROVED** [review]
