### PR TITLE
public_key: Handle key params only present in SignatureAlgorithm of  a cert

### LINKED ISSUE #9632: RSASSA-PSS Signature Verification Fails
**Describe the bug**

When verifying certificate signatures using the public_key API in Erlang (27), certificates signed with RSA-PSS (generated with the options `-sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:20`) fail to verify. The signature verification fails in an escript that calls `public_key:pkix_verify/2` even though OpenSSL verifies the certificate chain correctly. Certificates generated without these RSA-PSS options (i.e. signed with the default RSA-PKCS#1 v1.5) verify as expected.

Here is how the issue look like in a real TLS handshake.
```
=NOTICE REPORT==== 24-Mar-2025::18:19:16.213349 ===
TLS client: In state wait_cert at ssl_handshake.erl:2192 generated CLIENT ALERT: Fatal - Bad Certificate
 - invalid_signature
{error,{tls_alert,{bad_certificate,"TLS client: In state wait_cert at ssl_handshake.erl:2192 generated CLIENT ALERT: Fatal - Bad Certificate\n invalid_signature"}}}
```

**To Reproduce**

1. Issue certificate 
    ```
    # generate a key
    openssl genpkey -algorithm RSA-PSS -pkeyopt rsa_keygen_bits:2048 -out "client.key"
    # generate csr
    openssl req -sha256 -new -key client.key -out client.csr -nodes -subj /C=SE/ST=Stockholm/L=Stockholm/O=MyOrgName/OU=MyServiceClient/CN=localhost -addext basicConstraints=critical,CA:false
    # issue the cert by issuer.pem with rsa-pss options
    openssl x509 -req -CA issuer.pem -CAkey issuer.key -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:20 -in client.csr -out cert.pem -days 3650 -CAcreateserial
    ```

2. Verify `public_key:pem_entry_decode/2`

    Provided a escript in this attached file for reference: [test-cert.tar.gz](https://github.com/user-attachments/files/19437296/test-cert.tar.gz)

**Expected behavior**

OTP’s `public_key:pkix_verify/2` should correctly decode and verify the signature of a certificate signed with RSASSA-PSS when the certificate includes valid PSS parameters. The verification should succeed just as it does when using the OpenSSL verification command.

**Affected versions**

ALL?

### PR DESCRIPTION
**Pull request by IngelaAndin**
closes #9632

### CODE REVIEW

File: lib/public_key/test/public_key_SUITE.erl [hunk 1]
```diff
@@ -527,7 +530,7 @@ eddsa_pub() ->
 eddsa_pub(Config) when is_list(Config) ->
     Datadir = proplists:get_value(data_dir, Config),
     {ok, EDDSAPubPem} = file:read_file(filename:join(Datadir, "public_eddsa.pem")),
-    [{'SubjectPublicKeyInfo', _, not_encrypted} = Key] = PemEntry =
+    [{'SubjectPublicKeyInfo', _, not_encrypted}] = PemEntry =
         public_key:pem_decode(EDDSAPubPem),
     EDDSAPubKey = public_key:pem_entry_decode(PemEntry),
```
[the remark this answers is not in the document]
Comment (IngelaAndin) [reply lib/public_key/test/public_key_SUITE.erl]: Fix the test case, first attempt here to fix it was wrong as test case was wrong.

File: lib/public_key/test/public_key_SUITE.erl [hunk 2]
```diff
@@ -1458,6 +1461,169 @@ general_name(Config) when is_list(Config) ->
...
+    Intermediate = intermediate_cert(),
+    Entity = entity_cert(),
+    {ok,{{?'id-RSASSA-PSS',
+          #'RSAPublicKey'{},
+          asn1_NOVALUE},
+         []}} = 
+        public_key:pkix_path_validation(Root, [Intermediate, Entity],
+                                        [{verify_fun, Verify}]).
+
+root_cert() ->
```
[the remark this answers is not in the document]
Comment (IngelaAndin) [reply lib/public_key/test/public_key_SUITE.erl]: I put them at the end instead.

File: lib/public_key/src/pubkey_cert.erl [hunk 3]
```diff
@@ -2195,3 +2196,20 @@ otp_cert(#'OTPCertificate'{} = Cert) ->
...
+                        } = TBSCert,
+    %% Sometimes parameters may be missing in issuer's "SubjectPublicKeyInfo" but included in
+    %% the certs "SignatureAlgorithm" for RSA PSS signatures.
+    case Algo of
+        ?'id-RSASSA-PSS' ->
+            KeyParams;
+        _ ->
+            Params
+    end;
+key_params(_, KeyParams) ->
```
Comment (u3s) [inline lib/public_key/src/pubkey_cert.erl:2210]: Use same `Params` variable name for 2nd argument as in previous function clause?
`KeyParams` refers to different things between function clauses. maybe if avoided, reading would easier .

File: lib/public_key/src/pubkey_cert.erl [hunk 4]
```diff
@@ -2195,3 +2196,20 @@ otp_cert(#'OTPCertificate'{} = Cert) ->
...
+
+key_params(#'OTPCertificate'{tbsCertificate = TBSCert}, Params) when Params == asn1_NOVALUE;
+                                                                     Params == 'NULL' ->
+    #'OTPTBSCertificate'{signature =
+                             #'SignatureAlgorithm'{algorithm = Algo,
+                                                   parameters = KeyParams}
+                        } = TBSCert,
+    %% Sometimes parameters may be missing in issuer's "SubjectPublicKeyInfo" but included in
+    %% the certs "SignatureAlgorithm" for RSA PSS signatures.
+    case Algo of
```
Comment (u3s) [inline lib/public_key/src/pubkey_cert.erl]: maybe this case is not needed?

- if you match on `?'id-RSASSA-PSS'` in function head
- 2nd case clause would be handled by existing 2nd function clause

File: lib/public_key/test/public_key_SUITE.erl [hunk 5]
```diff
@@ -1458,6 +1461,34 @@ general_name(Config) when is_list(Config) ->
...
 				    authorityCertSerialNumber = 
 					1}).
+%%--------------------------------------------------------------------
+
+pkix_pss_params_in_signalg() ->
+    [{doc, "Test that we can verify chain without RSA-PSS params in subjectPublickeyInfo, "
+   "but supplied in signature algorithm identifier record instead"}].
+pkix_pss_params_in_signalg(Config) when is_list(Config) ->
+    %% Use some pre-generated certificates, we do not care when they happen
+    %% to expire, we are testing that we handle RSA-PSS params.
```
Comment (u3s) [inline lib/public_key/test/public_key_SUITE.erl:1471]: include GH issue number for future reference?

**Review by u3s — CHANGES_REQUESTED** [review]
is this anyhow covered in RFCs?

File: lib/public_key/test/public_key_SUITE.erl (hunk 5 above)
Comment (IngelaAndin) [reply lib/public_key/test/public_key_SUITE.erl:1471]: The GH issue will be referred by the  OTP-ticket and the merge commit so I think it is traceable enough.

File: lib/public_key/src/pubkey_cert.erl (hunk 4 above)
Comment (IngelaAndin) [reply lib/public_key/src/pubkey_cert.erl]: I did not due avoiding long lines, but I split it differently so as to be able to match in function head which I normally prefer.

File: lib/public_key/src/pubkey_cert.erl (hunk 3 above)
Comment (IngelaAndin) [reply lib/public_key/src/pubkey_cert.erl:2210]: That depends on how you think about it. I use the KeyParams for what should be used and returned.  But in the new solution I call it KeyParams0 that is checked for having no value in the RSA clause.

**Comment by IngelaAndin** [comment]
> is this anyhow covered in RFCs?

Not explicitly. I think the ASN.1 specs makes it quite possible and it makes sense for RSA keys as you can then upgrade an existing intermediat RSA cert to an RSA-PSS-PSS cert without changing the intermediate cert. And OpenSSL will verify this chain.

File: lib/public_key/src/pubkey_cert.erl [hunk 6]
```diff
@@ -2195,3 +2196,13 @@ otp_cert(#'OTPCertificate'{} = Cert) ->
     Cert;
 otp_cert(#cert{otp = OtpCert}) ->
     OtpCert.
+
+key_params(#'OTPTBSCertificate'{signature =
```
Comment (u3s) [inline lib/public_key/src/pubkey_cert.erl:2200]: indeed the formatting is now worse.
why not do it something like?

```
key_params(#'OTPTBSCertificate'{
              signature = #'SignatureAlgorithm'{
                             algorithm = ?'id-RSASSA-PSS',
                             parameters = KeyParams}},
           KeyParams0) when KeyParams0 == asn1_NOVALUE; KeyParams0 == 'NULL' ->
    %% Sometimes parameters may be missing in issuer's "SubjectPublicKeyInfo"
    %% but included in the certs "SignatureAlgorithm" for RSA PSS signatures.
    KeyParams;
key_params(_, KeyParams) ->
    KeyParams.
```

Comment (IngelaAndin) [reply lib/public_key/src/pubkey_cert.erl:2200]: It would have been much worse if I had not removed the outer record, now dereferenced here  
`key_params(OtpCert#'OTPCertificate'.tbsCertificate, KeyParams0),`
 Maybe I can reformat but only as the emacs mode indents I will no do my own indentation.

Comment (u3s) [reply lib/public_key/src/pubkey_cert.erl:2200]: above is just emacs.

Comment (IngelaAndin) [reply lib/public_key/src/pubkey_cert.erl:2200]: Well I settled for

```
key_params(#'OTPTBSCertificate'{signature =
                                    #'SignatureAlgorithm'{algorithm =
                                                              ?'id-RSASSA-PSS',
                                                          parameters = KeyParams}},
           KeyParams0) when KeyParams0 == asn1_NOVALUE;
                                          KeyParams0 == 'NULL' ->
    %% Sometimes parameters may be missing in issuer's
    %% "SubjectPublicKeyInfo" but included in the certs
    %% "SignatureAlgorithm" for RSA PSS signatures.
    KeyParams;
key_params(_, KeyParams) ->
    KeyParams.

```

I guess I feel it is unnatural to break already after "{"  in the record name, but that looks ok too.
