### PR TITLE
Fix code generation in guard for not (X =:= true)

### LINKED ISSUE #5007: Compiler emits invalid code when using a guard with not (X =:= true)
**To Reproduce**

Take this code:

```erl
-module(foo).
-export([bar/1]).

bar(X) when not (X =:= true) -> ok;
bar(_) -> error.
```

Then the following session:

```
$ erl
Erlang/OTP 24 [erts-12.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Eshell V12.0  (abort with ^G)
1> foo:bar(true).
error
2> foo:bar(foo).
error
```

The last call should have returned `ok` instead.

**Expected behavior**

```
1> foo:bar(true).
error
2> foo:bar(foo).
ok
```

**Affected versions**

I have verified it on Erlang/OTP 24, compiler-8.0. I will be glad to check other versions if necessary.

### PR DESCRIPTION
**Pull request by bjorng**
In a guard, `not (X =:= true)` would incorrectly evaluate to `false`
for non-boolean values of `X`.

The reason for the bug is an unsafe transformation in the `v3_core`
pass that transforms `not (X =:= true)` to `X =:= false`. That
transformation is safe only if `not (X =:= true)` was transformed from
`not X` by the compiler itself. (This bug was introduced in OTP R13.)

Eliminate the problem by only doing the transformation when `X =:= true`
is known to have been expanded from `not X` by the compiler.

While at it, also improve the comments.

Fixes #5007.

### CODE REVIEW

File: lib/compiler/src/v3_core.erl [hunk 1]
```diff
@@ -400,13 +400,32 @@ gexpr_bool(Op, L, R, Bools0, St0, Line) ->
...
+            %%
+            %%    not Expr  ==>  Expr =:= false
+            %%
+            %% which will produce the same result, but may eliminate
+            %% redundant is_boolean/1 tests (see unforce/3).
+            %%
+            %% Note that this tranformation would not be safe if the
+            %% original expression had been:
+            %%
+            %%    Expr =:= true
```
Comment (mikpe) [inline lib/compiler/src/v3_core.erl:428]: nit: `not(Expr =:= true)`

**Review by mikpe — APPROVED** [review]
