### PR TITLE
Fix zip:extract/2 with keep_old_files to respect cwd

### LINKED ISSUE #9087: zip:extract/2 with keep_old_files does not respect cwd
**Describe the bug**

When calling `zip:extract/2` with `keep_old_files` and `cwd` options, the `cwd` option is effectively ignored for the old file check. As a result, the old files are always replaced.

**To Reproduce**

```shell
# Create test.zip
$ mkdir test && touch test/foo.txt test/bar.txt && zip -r test.zip test && rm -rf test
  adding: test/ (stored 0%)
  adding: test/foo.txt (stored 0%)
  adding: test/bar.txt (stored 0%)
$ ls
test.zip
$ erl
Erlang/OTP 27 [erts-15.0] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Eshell V15.0 (press Ctrl+G to abort, type help(). for help)
# With cwd (1)
1> zip:extract("test.zip", [verbose, keep_old_files, {cwd, "nested"}]).
extracting: "test/foo.txt"
extracting: "test/bar.txt"
{ok,["nested/test/foo.txt","nested/test/bar.txt"]}
# With cwd (2) - replaces existing files, unexpected (!)
2> zip:extract("test.zip", [verbose, keep_old_files, {cwd, "nested"}]).
extracting: "test/foo.txt"
extracting: "test/bar.txt"
{ok,["nested/test/foo.txt","nested/test/bar.txt"]}
# Without cwd (1)
3> zip:extract("test.zip", [verbose, keep_old_files]).
extracting: "test/foo.txt"
extracting: "test/bar.txt"
{ok,["test/foo.txt","test/bar.txt"]}
# Without cwd (2) - keeps existing files as expected
4> zip:extract("test.zip", [verbose, keep_old_files]).
{ok,[]}
# With cwd (3) - now it keeps existing files, because it checks for the "test" top-level directory
5> zip:extract("test.zip", [verbose, keep_old_files, {cwd, "nested"}]).
{ok,[]}
```

**Expected behavior**

`keep_old_files` to respect `cwd`.

**Affected versions**

Tested with 27.0.

### PR DESCRIPTION
**Pull request by jonatanklosko**
Closes #9087.

### CODE REVIEW

File: lib/stdlib/src/zip.erl [hunk 1]
```diff
@@ -997,14 +997,15 @@ verbose_zip(FN) ->
...
     lists:member(FileName, List);
 file_in_list(_, _) ->
     false.
 
-keep_old_file({#zip_file{name = FileName},_}) ->
-    not (filelib:is_file(FileName) orelse filelib:is_dir(FileName));
-keep_old_file(_) ->
+keep_old_file(#zip_file{name = FileName}, CWD) ->
+    FileName1 = add_cwd(CWD, FileName),
+    not (filelib:is_file(FileName1) orelse filelib:is_dir(FileName1));
```
Comment (jonatanklosko) [inline lib/stdlib/src/zip.erl:1007]: The main fix is here, we add CWD before making file system checks.

**Comment by garazdawi** [comment]
Thanks! Merged for release in 27.2.
