### PR TITLE
stdlib: cache code:get_docs calls when completing types in the shell

### LINKED ISSUE #9215: edlin expansion takes ~15s for erl_syntax
**Describe the bug**
In the context of #WhatsApp/erlang-language-platform/issues/70, I started playing around with `edlin` auto-completion and noticed it can be very slow for certain functions.

**To Reproduce**
```
1> timer:tc(fun() -> edlin_expand:expand(lists:reverse("erl_syntax:concrete("),[]) end).
```

This takes almost 15s for me the first time. Then, the result is cached.

**Expected behavior**
Completions are provided much faster.

**Affected versions**
OTP 27

### PR DESCRIPTION
**Pull request by frazze-jobb**
closes #9215

### CODE REVIEW

File: lib/stdlib/src/edlin_type_suggestion.erl [hunk 1]
```diff
@@ -220,10 +220,19 @@ simplified_type(file, name_all, 0) -> {type, erlang, string, []};
 simplified_type(file, name, 0) -> {type, erlang, string, []};
 simplified_type(_Module, _TypeName, _Arity) -> none.
 
+code_get_doc_cache(Mod) ->
+    case get(Mod) of
```
Comment (garazdawi) [inline lib/stdlib/src/edlin_type_suggestion.erl:224]:
```suggestion
    case get({?MODULE, Mod}) of
```

I suggest that we tag the value with something so that we reduce the chances of colliding with other code.

**Review by garazdawi — APPROVED** [review]
