### PR TITLE
asn1: Don't pass on the undec_rest option to the Erlang compiler

### LINKED ISSUE #8779: Typo in asn1 flag name?
**Describe the bug**
Typo in asn1 flag name?

**To Reproduce**

**Expected behavior**

**Affected versions**
HEAD

**Additional context**
On line [1385](https://github.com/erlang/otp/blob/e54c6ec27c07861a057678009833c3b4ef49dd46/lib/asn1/src/asn1ct.erl#L1385) of `/lib/asn1/src/asn1ct.erl` it looks like a typo of the flag name.  It is `undec_rec` which doesn't appear anywhere else in the repo however there is an `asn1ct` flag named `undec_rest`.

### PR DESCRIPTION
**Pull request by bjorng**
Closes #8779

### CODE REVIEW

File: lib/asn1/src/asn1ct.erl [hunk 1]
```diff
@@ -1382,7 +1382,7 @@ is_asn1_flag(no_ok_wrapper) -> true;
 is_asn1_flag(optimize) -> true;
 is_asn1_flag(per) -> true;
 is_asn1_flag({record_name_prefix,_}) -> true;
-is_asn1_flag(undec_rec) -> true;
+is_asn1_flag(undec_rest) -> true;
```
Comment (vkatsuba) [inline lib/asn1/src/asn1ct.erl:1385]: Maybe it make sense to cover this logic by some tests to avoid similar issues in the future.
