### PR TITLE
ssh: fix decode uid, gid

### LINKED ISSUE #7895: ssh_sftp:write_file_info/3,4 returns {error,failure}
**Describe the bug**
`ssh_sftp:write_file_info` constantly returns `{error,failure}`.

**To Reproduce**
1. Generate host keys in /tmp/ssh
2. Run this script that starts ssh daemon locally and connect to it, performing operations:

``` erlang
#!/usr/bin/env escript                                                                                                                                    
                                                                                                                                                          
-include_lib("kernel/include/file.hrl").                                                                                                                  
                                                                                                                                                          
-define(SSH_PORT, 31000).                                                                                                                                 
                                                                                                                                                          
main(_) ->                                                                                                                                                
    {ok, _} = application:ensure_all_started(ssh),                                                                                                        
                                                                                                                                                          
    SshDaemonOpts = [                                                                                                                                     
        {system_dir, "/tmp/ssh"},                                                                                                       
        {password, "test"}                                                                                                                                
    ],                                                                                                                                                    
    {ok, _} = ssh:daemon(?SSH_PORT, SshDaemonOpts),                                                                                                       
                                                                                                                                                          
    ConnOpts = [                                                                                                                                          
        {password, "test"},                                                                                                                               
        {silently_accept_hosts, true},                                                                                                                    
        {preferred_algorithms, ssh:default_algorithms()}                                                                                                  
    ],                                                                                                                                                    
    {ok, ConnectionRef} = ssh:connect("localhost", ?SSH_PORT, ConnOpts),                                                                                  
    {ok, Pid} = ssh_sftp:start_channel(ConnectionRef),                                                                                                    
                                                                                                                                                          
    ok = ssh_sftp:write_file(Pid, "/tmp/file", <<"Test">>),                                                                                               
    {ok, FileInfo} = file:read_file_info("/tmp/file"),                                                                                                    
    Result = ssh_sftp:write_file_info(Pid, "/tmp/file", FileInfo#file_info{mode = 8#00777}),                                                              
                                                                                                                                                          
    io:format("File info: ~p~n", [FileInfo]),                                                                                                             
    io:format("Result: ~p~n", [Result]).        
``` 
The script prints:
```
File info: {file_info,4,regular,read_write,
                      {{2023,11,21},{18,19,45}},
                      {{2023,11,21},{18,19,45}},
                      {{2023,11,21},{18,19,45}},
                      33188,1,53,0,12978347,1000,1000}
Result: {error,failure}
```

**Expected behavior**
`ssh_sftp:write_file_info` either works fine ( which is expected in the script above) or prints meaningful error message. But never just "failure".

**Affected versions**
 Reproduced on both OTP 24.2 and 26.1.2.

### LINKED ISSUE #7897: Both ssh_sftp:read_file_info/2,3 and ssh_sftp:read_link_info/2,3 return incorrect record file_info
**Describe the bug**
`ssh_sftp:read_file_info/2,3` and `ssh_sftp:read_link_info/2,3` return record `file_info` with `uid` and `gid` string values, while they must be integers. 

**To Reproduce**
Read any file via one of those functions.

**Expected behavior**
`ssh_sftp:read_file_info/2,3` and `ssh_sftp:read_link_info/2,3` return the record in the same format as functions with the same names from `file` module.

**Affected versions**
Reproduced on 24.2 and 26.1.2, but in the past was reproduced on older OTP versions as well.

**Additional context**
The incorrect record can't be used as is, because functions like `ssh_stfp:write_file_info` raise exceptions because incorrect type of `uid` and `gid` in the record.

### PR DESCRIPTION
**Pull request by u3s**
- adds missing list_to_integer conversion upon decoding
- fix version typo
- enhanced tests
- closes #7897
- closes #7895

### CODE REVIEW

File: lib/ssh/src/ssh_xfer.erl [hunk 1]
```diff
@@ -736,7 +736,7 @@ decode_As(Vsn, [{AName, AField}|As], R, Flags, Tail) ->
 	    decode_As(Vsn, As, setelement(AField, R, X), Flags, Tail2);
 	ownergroup when ?is_set(?SSH_FILEXFER_ATTR_OWNERGROUP, Flags),Vsn>=5 ->
 	    <<?UINT32(Len), Bin:Len/binary, Tail2/binary>> = Tail,
-	    X = binary_to_list(Bin),
+	    X = list_to_integer(binary_to_list(Bin)),
```
Comment (IngelaAndin) [inline lib/ssh/src/ssh_xfer.erl:739]: Why not use binary_to_integer ?

**Review by IngelaAndin — APPROVED** [review]
