### PR TITLE
Correct coverage for functions on the same line

### LINKED ISSUE #8159: cover with native coverage with two functions in the same line is order dependent
**Describe the bug**

cover with native coverage on OTP 27 with two functions in the same line returns different results based on the order the functions are called.

**To Reproduce**

Take the following file `foo.erl`:

```erlang
-module(foo).
-export([bar/0, baz/0]).

bar() -> ok. baz() -> not_ok.
```

and now the `erl` session:

```erlang
1> cover:compile_module("foo").
{ok,foo}
2> foo:bar().
ok
3> cover:analyse().
{result,[{{foo,bar,0},{0,1}},{{foo,baz,0},{0,1}}],[]}
```

Notice how it says none of the functions are covered. Erlang/OTP 26 would return `{result,[{{foo,bar,0},{1,0}},{{foo,baz,0},{0,1}}],[]}` instead.

Now check out this new `erl` session:

```erlang
1> cover:compile_module("foo").
{ok,foo}
2> foo:baz().
ok
3> cover:analyse().
{result,[{{foo,bar,0},{1,0}},{{foo,baz,0},{1,0}}],[]}
```

Now it shows *both* as covered, even if `foo:bar()` was never called.

I have tried to isolate this using only the coverage API and I could not reproduce. The coverage API would correctly return:

```
1> foo:bar(), code:get_coverage(line, foo).
[{4,1},{4,0}]
```

Once I started debugging cover, I found this line:

https://github.com/erlang/otp/blob/423f65167a42884c1fc12ac36c46c85fd7c16071/lib/tools/src/cover.erl#L2284

Which explains the error: if you have several functions in the same line, the last one will always win. Perhaps `get_coverage(line, Mod)` should also return the function the coverage pertains to? And then we match that against the `function` and `arity` in `#bump`?

**Expected behavior**

Erlang/OTP 26 returns `{result,[{{foo,bar,0},{1,0}},{{foo,baz,0},{0,1}}],[]}`.

**Affected versions**

27 RC1.

**Additional context**

Thank you for Erlang 27!

### PR DESCRIPTION
**Pull request by bjorng**
This pull request fixes the bug reported in #8159.

It also eliminates a weird behavior when there are multiple functions on the same line. Consider this module:

    -module(foo).
    -export([bar/0, baz/0]).

    bar() -> ok. baz() -> not_ok.

In Erlang/OTP 26, analysing on the line level would return two entries for line 4:

    1> cover:compile_module(foo).
    {ok,foo}
    2> foo:bar().
    ok
    3> cover:analyse(foo, coverage, line).
    {ok,[{{foo,4},{1,0}},{{foo,4},{0,1}}]}
    4> cover:analyse(foo, calls, line).
    {ok,[{{foo,4},1},{{foo,4},0}]}

This has been changed to coalesce all information about each line to a single entry in the resulting list:

    1> cover:compile_module(foo).
    {ok,foo}
    2> foo:bar().
    ok
    3> cover:analyse(foo, coverage, line).
    {ok,[{{foo,4},{1,0}}]}
    4> cover:analyse(foo, calls, line).
    {ok,[{{foo,4},1}]}

Closes #8159

### CODE REVIEW

File: lib/compiler/src/beam_disasm.erl [hunk 1]
```diff
@@ -1308,8 +1308,8 @@ resolve_inst({bs_match,[{Fail,Ctx,{z,1},{u,_},Args}]},_,_,_) ->
 %% OTP 27.
 %%
 
-resolve_inst({executable_line,[Index]},_,_,_) ->
-    {line,resolve_arg(Index)};
+resolve_inst({executable_line,[Location,Index]},_,_,_) ->
+    {line,resolve_arg(Location),resolve_arg(Index)};
```
Comment (the-mikedavis) [inline lib/compiler/src/beam_disasm.erl:1312]: Should this be translated as `{executable_line,Location,Index}` instead? I was about to open a separate pull to suggest this since it's useful to know the difference between line and executable_line but now I think it makes even more sense since it's no longer the same as `{line,Index}`

```suggestion
    {executable_line,resolve_arg(Location),resolve_arg(Index)};
```

Comment (bjorng) [reply lib/compiler/src/beam_disasm.erl]: Thanks for noticing this. Fixed!
