### PR TITLE
public_key: Add support for ExtensionRequest

### LINKED ISSUE #10028: no function clause matching public_key:get_asn1_module('ExtensionRequest')
**Describe the bug**

Thanks to the latest fixes in public_key (including https://github.com/erlang/otp/issues/10001), most of the code that worked with OTP 27 now seems to be working again... except one case that still fails:

```erlang
public_key:der_encode('ExtensionRequest', []).

** exception error: no function clause matching public_key:get_asn1_module('ExtensionRequest') (public_key.erl:590)
     in function  public_key:der_encode/2 (public_key.erl:833)
```

**To Reproduce**

Since OTP 28.0-rc4, including 28.0.1, it fails:
```sh
$ erl28-rc4
Erlang/OTP 28 [RELEASE CANDIDATE 4] [erts-16.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit:ns]
Eshell V16.0 (press Ctrl+G to abort, type help(). for help)
1> public_key:der_encode('ExtensionRequest', []).
** exception error: no function clause matching public_key:get_asn1_module('ExtensionRequest') (public_key.erl:575)
     in function  public_key:der_encode/2 (public_key.erl:800)

$ erl28
Erlang/OTP 28 [erts-16.0.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit:ns]
Eshell V16.0.1 (press Ctrl+G to abort, type help(). for help)
1> public_key:der_encode('ExtensionRequest', []).
** exception error: no function clause matching public_key:get_asn1_module('ExtensionRequest') (public_key.erl:590)
     in function  public_key:der_encode/2 (public_key.erl:833)
```

**Expected behavior**

Before OTP 28.0-rc4, it worked perfectly:
```sh
$ erl27
Erlang/OTP 27 [erts-15.2.7] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit:ns]
Eshell V15.2.7 (press Ctrl+G to abort, type help(). for help)
1> public_key:der_encode('ExtensionRequest', []).
<<48,0>>

$ erl28-rc3
Erlang/OTP 28 [RELEASE CANDIDATE 3] [erts-16.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit:ns]
Eshell V16.0 (press Ctrl+G to abort, type help(). for help)
1> public_key:der_encode('ExtensionRequest', []).
<<48,0>>
```

**Affected versions**

OTP 28.0-rc4 up to 28.0.1. Looking at "master" git branch, it's probably still affected.

### PR DESCRIPTION
**Pull request by IngelaAndin**
Add modern ASN-1 specs to be able to retain support for ExtensionRequest from legacy PKCS-9 spec.

This can open up for further support being added later.

Closes #10028

### CODE REVIEW

File: lib/public_key/src/public_key.erl [hunk 1]
```diff
@@ -563,6 +563,13 @@ der_decode('Dss-Sig-Value', Der) ->
 	error:{badmatch, {error, _}} = Error ->
 	    erlang:error(Error)
     end;
+%% Bakwards compatibility
```
Comment (u3s) [inline lib/public_key/src/public_key.erl]: global typo: `Bakwards` -> `Backwards` (or maybe should be `Backward` here?)

**Review by u3s — APPROVED** [review]

File: lib/public_key/src/public_key.erl (hunk 1 above)
Comment (IngelaAndin) [reply lib/public_key/src/public_key.erl]: fixed

File: lib/public_key/src/public_key.erl [hunk 2]
```diff
@@ -815,6 +824,14 @@ der_encode('Dss-Sig-Value', Entity) ->
...
```
Comment (u3s) [inline lib/public_key/src/public_key.erl]: global typo, which you fixed above not here. run grep please.

**Review by u3s — APPROVED** [review]

File: lib/public_key/src/public_key.erl (hunk 2 above)
Comment (IngelaAndin) [reply lib/public_key/src/public_key.erl]: @u3s  I did, maybe it was that it was the first word here so that it started with B and not b ! Fixed anyhow please re-approve.

**Review by u3s — APPROVED** [review]
