### PR TITLE
Fix a tail recursion bug

### LINKED ISSUE #9190: xmerl_sax_parser:stream/2 stack keeps growing until the VM is OOM
**Describe the bug**
The `stack_size` of the process running `xmerl_sax_parser:stream/2` keeps growing.

**To Reproduce**
Use `xmerl_sax_parser:stream/2` on a large file and observe the stack growing by checking `process_info(Pid, stack_size)`.

**Expected behavior**
I expect the stream parser to handle infinite stream without blowing up the stack.

**Affected versions**
Tested on 27.2 but seems all versions are affected.

**Additional context**
I used `xmerl_sax_parser:stream/2` to parse the XML stream from an ejabberd server and noticed after a while the VM is killed by the OOM killer. After some inspection the process has a huge stack_size that keeps growing.

I also verified that removing the error handling in the first two clauses of `xmerl_sax_parser_utf8:parse_content/4` and keeping just the cf/5 calls i.e. making it tail-recursive, the stack size is constant.

### PR DESCRIPTION
**Pull request by lthor**
- Rewrote some recursion when calling continuation fun to get more data.
- Remove all  old style catch calls
Fixes #9190

### CODE REVIEW

File: lib/xmerl/src/xmerl_scan.erl [hunk 1]
```diff
@@ -2881,11 +2882,11 @@ scan_reference("#" ++ T, S0) ->
...
-    case catch scan_entity_ref(T, S) of
-	{'EXIT', _} ->
-	    ?fatal(error_scanning_entity_ref,S);
-	Other ->
-	    Other
+    try
+        scan_entity_ref(T, S)
+    catch
+	exit:_ ->
+	    ?fatal(error_scanning_entity_ref,S)
```
Comment (dgud) [inline lib/xmerl/src/xmerl_scan.erl:2889]: error ?

File: lib/xmerl/src/xmerl_scan.erl [hunk 2]
```diff
@@ -3939,17 +3940,15 @@ predefined_entity(_) ->    false.
...
-	{'EXIT',{cyclic,_}} ->
-	    ?fatal({illegal_recursion_in_Entity, EName}, S);
-	DG ->
+    try sofs:family_to_digraph(Set, [acyclic]) of
+        DG ->
 	    digraph:delete(DG),
-	    ok
+            ok
+    catch
+        exit:{'EXIT',{cyclic,_}} ->
```
Comment (dgud) [inline lib/xmerl/src/xmerl_scan.erl:3948]: sofs do error not exit

```suggestion
        error:{'EXIT',{cyclic,_}} ->
```

**Review by dgud — APPROVED** [review]

File: lib/xmerl/src/xmerl_scan.erl (hunk 2 above)
Comment (lthor) [reply lib/xmerl/src/xmerl_scan.erl:3948]: Fixed, should be:  error:{cyclic,_} ->

File: lib/xmerl/src/xmerl_scan.erl (hunk 1 above)
Comment (lthor) [reply lib/xmerl/src/xmerl_scan.erl:2889]: This should be an exit, double checked the code.

**Review by dgud — APPROVED** [review]
