### PR TITLE
Fix beam crash when resetting call_time/memory while tracing

### LINKED ISSUE #8835: 27.1 crash (core dump) while running `tprof`
**Describe the bug**
I wanted to use `tprof` on a running RabbitMQ node and the Beam crashed completely. I submitted a bunch of commands to the shell at once so I'm not sure which command was executing when it happened.

It looked like this:
```
> tprof:start(#{type => call_memory}), tprof:set_pattern('_', '_' , '_'), tprof:enable_trace(whereis(ra_log_wal)), timer:sleep(5000), Sample = tprof:collect().
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
[os_mon] memory supervisor port (memsup): Erlang has closed
make: *** [/home/kura/rabbitmq/server/ra-log-single-memtbl/deps/rabbit_common/mk/rabbitmq-run.mk:275: run-broker] Floating point exception (core dumped)
```

I've uploaded `beam.smp` and the core dump here:
https://drive.google.com/drive/folders/1VqXjDjNcvl06moBy4qbL7of1Ym4EEzQ9?usp=drive_link

**Affected versions**
27.1

### PR DESCRIPTION
**Pull request by sverker**
Fix #8835.

Resetting counters of `call_time` or `call_memory` tracing of a function while it's called by other process could cause the beam VM to crash. This is an old bug that has existed since OTP R16.

### CODE REVIEW

File: erts/emulator/test/trace_call_time_SUITE.erl [hunk 1]
```diff
@@ -685,6 +686,77 @@ spinner(N) ->
...
+    ok.
+
+loop_aaa_bbb() ->
+    aaa = aaa(),
+    bbb = bbb(),
+    receive die -> ok
+    after 0 -> loop_aaa_bbb()
+    end.
+
+
```
Comment (vkatsuba) [inline erts/emulator/test/trace_call_time_SUITE.erl:759]:
```suggestion
```
