### PR TITLE
ssl: Fix cert_auth check

### LINKED ISSUE #8356: Issue with SSL (tlsv1.3) communication in OTP 25 and OTP 26 compared to OTP 24
**Describe the bug**
I encountered an issue when using the `:ssl` with `tlsv1.3` module for SSL communication in Erlang/OTP 25 and OTP 26 compared to OTP 24.

**To Reproduce**

I used the following Erlang code to fetch data using SSL:

```erlang
-module(ssl_debug).
-export([run/0]).

run() ->
    SslOpts = [
        {verify, verify_peer},
        {cacertfile, "/path/to/ca.crt"},
        {certfile, "/path/to/client.crt"},
        {keyfile, "/path/to/client.key"},
        {keep_secrets, true},
        {versions, ['tlsv1.3']},
        {log_level, debug},
        {log_alert, true}
    ],
    Host = "mywebserver.com",
    Port = 443,
    io:format("Attempting SSL connection to ~s:~p~n", [Host, Port]),
    ssl:start(),
    case ssl:connect(Host, Port, SslOpts, 5000) of
        {ok, Socket} ->
            io:format("SSL connection established~n"),
            Path = "/myendpoint",
            Request = "GET " ++ Path ++ " HTTP/1.1\r\nHost: " ++ Host ++ "\r\n\r\n",
            case ssl:send(Socket, Request) of
                ok ->
                    io:format("Request sent~n");
                {error, SendReason} ->
                    io:format("Error sending request: ~p~n", [SendReason])
            end,
            io:format("Attempting SSL connection to ~s:~p~n", [Host, Port]),
            case receive_response(Socket, [], 3000) of
                {ok, Data} ->
                    io:format("Response:~n~s~n", [Data]);
                {error, ReceiveReason} ->
                    io:format("Error receiving response: ~p~n", [ReceiveReason])
            end,
            ok = ssl:close(Socket);
        {error, ConnectReason} ->
            io:format("SSL connection failed1: ~p~n", [ConnectReason]);
        Everything ->
            io:format("SSL connection failed2: ~p~n", [Everything])
    end.

receive_response(Socket, Acc, Timeout) ->
    receive
        {ssl, Socket, Data} ->
            io:format("Received data: ~p~n", [Data]),
            receive_response(Socket, [Acc, Data], Timeout);
        {ssl_closed, Socket} ->
            io:format("Socket closed~n"),
            {ok, iolist_to_binary(Acc)};
        {ssl_error, Socket, Reason} ->
            io:format("SSL error: ~p~n", [Reason]),
            {error, Reason};
        Everything ->
            io:format("SSL error: ~p~n", [Everything]),
            {error, "Error"}
    after Timeout ->
        io:format("Receive timeout after ~p milliseconds~n", [Timeout]),
        {ok, iolist_to_binary(Acc)}
    end.

```

The code worked perfectly on OTP 24, but it failed on both OTP 25 and OTP 26.

**Expected behavior**
I would expect to be able to connect to myserver on both OTP 25 and OTP 26.

**Affected versions**
**Erlang/OTP 26 [erts-14.2.2]** and **Erlang/OTP 25**

**Additional context**
If I use `:ssl` with `tlsv1.2` everything works on **Erlang/OTP 25** and **Erlang/OTP 25**
The problem seems to be with the `ssl_app` version. It changed from `{ssl_app,"10.7.3.5"` in **OTP 24** to `{ssl_app,"11.1.1"}` in OTP 26.
I also create this issue in elixir MINT library [here](https://github.com/elixir-mint/mint/issues/427).
Could you please investigate this issue and provide guidance on how to resolve it? Is there any workaround or fix available to ensure compatibility with the latest OTP releases?

### PR DESCRIPTION
**Pull request by IngelaAndin**
Include also end entity cert when selecting issuers for cert_auth extension check

Closes #8356

### CODE REVIEW

**Review by wattsnicky89 — APPROVED** [review]

File: lib/ssl/test/ssl_cert_SUITE.erl [hunk 1]
```diff
@@ -981,6 +984,25 @@ key_auth_ext_sign_only(Config) when is_list(Config) ->
     ssl_test_lib:basic_test(ClientOpts, ServerOpts, Config).
 
 %%--------------------------------------------------------------------
+cert_auth_in_first_ca() ->
+    [{doc,"Test cert auth will be available in firs ca in chain, make it happen by only having one"}].
```
Comment (samfrench) [inline lib/ssl/test/ssl_cert_SUITE.erl:988]: @IngelaAndin, thank you for fixing this for us. A minor comment about a typo in the test description for "first".

Comment (IngelaAndin) [reply lib/ssl/test/ssl_cert_SUITE.erl]: Thanks for noticing, fixed.
