### PR TITLE
fix: erts +t, +P, +Q arg overflow

### LINKED ISSUE #9668: Range check for atom table size option doesn't detect some invalid values
**Describe the bug**
When setting the size of the atom table using `erl +t`, certain invalid values that should be rejected are instead silently accepted and truncated. This happens on x86_64 for values greater than or equal to 2 ^ 32 + 8192, i.e. 4294975488.

**To Reproduce**
```
$ erl +t 4294975488
no more index entries in atom_tab (max=8192)

Crash dump is being written to: erl_crash.dump...done
```

Or with a slightly higher value:

```
$ erl +t 4295067296
Erlang/OTP 28 [RELEASE CANDIDATE 2] [erts-16.0] [source] [64-bit] [smp:22:22] [ds:22:22:10] [async-threads:1] [jit:ns]

Eshell V16.0 (press Ctrl+G to abort, type help(). for help)
1> erlang:system_info(atom_limit).
100000
```

**Expected behavior**
The argument should be rejected, as currently happens for 2 ^ 32 + 8191:
```
$ erl +t 4294975487
bad atom table size 4294975487
```

**Affected versions**
Tested with 27.2 and 28.0-rc2 on Linux x86_64.

**Additional context**
This happens [here](https://github.com/erlang/otp/blob/bef38b30beb0087e2f0fc0777d370ddade91c26d/erts/emulator/beam/erl_init.c#L2165) because `erl_start` assigns the return value of `strtol`, which returns a `long`, to `erts_atom_table_size`, which is an `int`, before checking whether the value is in range:

```
erts_atom_table_size = strtol(arg, NULL, 10);
```

As a result, 2^32 + 8192 gets truncated to 8192, which is equal to `MIN_ATOM_TABLE_SIZE` and therefore accepted.

Looking at other uses of `strtol` in that file, it seems like this also affects `+P` and `+Q`, for the maximum number of processes and ports.

### PR DESCRIPTION
**Pull request by MarkoMin**
Code pattern and naming is copied from similar cases from this file.

Should we add some testcases for it? If yes, where exactly? (my first contribution to ERTS...)

Props to issue author for clues.

Fixes #9668

### CODE REVIEW

File: erts/emulator/beam/erl_init.c [hunk 1]
```diff
@@ -2160,18 +2164,20 @@ erl_start(int argc, char **argv)
...
-		erts_atom_table_size > MAX_ATOM_TABLE_SIZE) {
+		val < MIN_ATOM_TABLE_SIZE ||
+		val > MAX_ATOM_TABLE_SIZE) {
 		erts_fprintf(stderr, "bad atom table size %s\n", arg);
 		erts_usage();
 	    }
 	    VERBOSE(DEBUG_SYSTEM,
-                    ("setting maximum number of atoms to %d\n",
+                    ("setting maximum number of atoms to %ld\n",
 		     erts_atom_table_size));
```
Comment (legoscia) [inline erts/emulator/beam/erl_init.c:2179]:
```suggestion
		     val));
```

Comment (MarkoMin) [reply erts/emulator/beam/erl_init.c:2179]: I'd rather stay with "%d" and `erts_atom_table_size` because that'd expose similar error if it happend

Comment (MarkoMin) [reply erts/emulator/beam/erl_init.c:2180]: Force pushed, I think it should be ok now

**Comment by MarkoMin** [comment]
I've removed build files and added a simple testcase

File: erts/test/erlexec_SUITE.erl [hunk 2]
```diff
@@ -492,6 +493,18 @@ long_path_env_when_rootdir_not_present(Config) when is_list(Config) ->
     ?assertEqual(string:length(string:find(Output, LongPath ++ pathsep() ++ LongPath)), (LongPathLength * 2) + string:length(pathsep())),
     ok.
 
+otp_9668(_Config) ->
```
Comment (garazdawi) [inline erts/test/erlexec_SUITE.erl:496]: Can you give the testcase a more descriptive name, like `too_large_argument_test` and then add a comment pointing to the issue/pr.

(The `otp_XYZ` refers to internal ticket numbers, not the github ones so the current name would be very confusing for future maintainers).

**Review by garazdawi — APPROVED** [review]

**Comment by garazdawi** [comment]
Thanks!
