### PR TITLE
ssl: Fix version mismatch

### LINKED ISSUE #5835: TLS Certificate Unknown in OTP 24.3
**Describe the bug**
After updating to OTP 24.3.2, we cannot establish an Elixir - HTTPoison connection to a server that requires a client certificate, instead we receive 

```elixir
{:error,
 %HTTPoison.Error{
   id: nil,
   reason: {:tls_alert,
    {:certificate_unknown,
     'TLS client: In state cipher received SERVER ALERT: Fatal - Certificate Unknown\n'}}
 }}
```

**To Reproduce**
Unfortunately this issues involves connecting to a private server of a partner that we cannot give access to; and we also do not have any access to the server in order to debug the requests. Please let me know about any debugging possibilities I should do to provide more information (see my attempts below)

**Expected behavior**
An established connection to the server.

**Affected versions**
(24.3,) 24.3.1 and 24.3.2, but not in 24.2.2

**Additional context**
When looking for an opportunity to debug the requests, I stumbled across `https://prod.idrix.eu/secure/`. I tested sending the requests against this server:

* OTP 24.2.2 worked as expected
* 24.3 returned `{:error, %HTTPoison.Error{id: nil, reason: :checkout_failure}}`
* 24.3.1 and 24.3.2 worked again (contrary to the server we are connecting to)

I then compared the outputs of requests of 24.2.2 and 24.3.2, and there are some whitespace related changes; however I do not know if is related in any way to the issue:

```diff
- [SSL_SECURE_RENEG] => true
+ [SSL_SECURE_RENEG] => true 

- [REQUEST_URI] => /secure/ 
+ [REQUEST_URI] => /secure/
```

Other differences are in `[SSL_SESSION_ID]`, `[REMOTE_PORT]`, `[REQUEST_TIME_FLOAT]` and `[REQUEST_TIME]`.

### PR DESCRIPTION
**Pull request by IngelaAndin**
The special case handled by the tls_gen_connection:effective_version
function is only valid in the hello and wait_sh state.

Closes #5835

### CODE REVIEW

**Review by KennethL — CHANGES_REQUESTED** [review]

File: lib/ssl/src/tls_gen_connection.erl [hunk 1]
```diff
@@ -751,19 +751,24 @@ next_record_done(#state{protocol_buffers = Buffers} = State, CipherTexts, Connec
...
+%% (before the versions is actually negotiated) will always be the value of TLS-1.2 (which is a legacy
+%% field in TLS-1.3 client hello). The versions are instead negotiated with an hello extension. When
+%% decoding the server_hello messages we want to go through TLS-1.3 decode functions to be able
+%% to handle TLS-1.3 extensions if TLS-1.3 will be the negotiated version.
+effective_version({3,3} , #{versions := [{3,4} = Version |_]}, client, StateName) when StateName == hello;
+                                                                                       StateName == wait_sh ->
     Version;
-%% Use highest supported version during startup (TLS server, all versions).
-effective_version(undefined, #{versions := [Version|_]}, _) ->
+%% When the negotiated_version variable is not yet set use the highest supported version.
```
Comment (IngelaAndin) [inline lib/ssl/src/tls_gen_connection.erl:767]:
```suggestion
%% When the `negotiated_version` variable is not yet set use the highest supported version.
```

File: lib/ssl/src/tls_gen_connection.erl [hunk 2]
```diff
@@ -751,19 +751,24 @@ next_record_done(#state{protocol_buffers = Buffers} = State, CipherTexts, Connec
...
+                                                                                       StateName == wait_sh ->
     Version;
-%% Use highest supported version during startup (TLS server, all versions).
-effective_version(undefined, #{versions := [Version|_]}, _) ->
+%% When the `negotiated_version` variable is not yet set use the highest supported version.
+effective_version(undefined, #{versions := [Version|_]}, _, _) ->
     Version;
-%% Use negotiated version in all other cases.
-effective_version(Version, _, _) ->
+%% In all other cases use version saved in the connection state variable negotiated_version
```
Comment (IngelaAndin) [inline lib/ssl/src/tls_gen_connection.erl:770]:
```suggestion
%% In all other cases use the version saved in the connection state variable `negotiated_version`
```

File: lib/ssl/src/tls_gen_connection.erl [hunk 3]
```diff
@@ -751,19 +751,24 @@ next_record_done(#state{protocol_buffers = Buffers} = State, CipherTexts, Connec
...
-%% be able to process new TLS 1.3 extensions, the effective version shall be set
-%% {3,4}.
-%% When highest supported version is {3,4} the negotiated version is set to {3,3}.
-effective_version({3,3} , #{versions := [Version|_]}, client) when Version >= {3,4} ->
+
+%% Pre TLS-1.3, on the client side, the connection state variable `negotiated_version` will initially be
+%% the requested version. On the server side the same variable is initially undefined.
+%% When the client can support TLS-1.3 and one or more prior versions and we are waiting
+%% for the server hello (with or without a RetryRequest, that is in state hello or in state wait_sh),
+%% the "initial requested version" kept in the connection state variable negotiated_version
```
Comment (IngelaAndin) [inline lib/ssl/src/tls_gen_connection.erl:759]:
```suggestion
%% the "initial requested version" kept in the connection state variable `negotiated_version`
```
