### PR TITLE
ssl:  Improve error message

### LINKED ISSUE #10007: Confusing error from ssl:connect/3 when Host is a binary
**Describe the bug**

The error reported by `ssl:connect/3` when `Host` is a binary (or otherwise not a string?) is confusing/misleading:

```
1> application:ensure_all_started(ssl).
{ok,[crypto,asn1,public_key,ssl]}
2> ssl:connect(<<"localhost">>, 55156, [{verify, verify_none}]).
{error,{options,{socket_options,[{packet_size,0},
                                 {packet,0},
                                 {header,0},
                                 {active,false},
                                 {mode,binary}]}}}
```

**Expected behavior**

A `badarg` error/exception or similar. Not something that complains about `socket_options`, anyway.

**Affected versions**

OTP-26.x, OTP-27.x, OTP-28.0.1

### PR DESCRIPTION
**Pull request by IngelaAndin**
closes #10007

### CODE REVIEW

File: lib/ssl/src/tls_socket.erl [hunk 1]
```diff
@@ -140,11 +140,14 @@ connect(Address, Port,
...
-	    {error, {options, {socket_options, UserOpts}}}
+            ConStr = lists:flatten(io_lib:format("~p:connect(~p, ~p, ~p, ~p)", [Transport,Host, Port, UserOpts, Timeout])),
+	    {error, {badarg, ConStr}};
+        exit:badarg ->
+            ConStr = lists:flatten(io_lib:format("~p:connect(~p, ~p, ~p, ~p)", [Transport,Host, Port, UserOpts, Timeout])),
+	    {error, {badarg, ConStr}};
+	exit:{badarg, Reason} ->
+            ConStr = lists:flatten(io_lib:format("~p:connect(~p, ~p, ~p, ~p)", [Transport,Host, Port, UserOpts, Timeout])),
+	    {error, {badarg, Reason, ConStr}}
     end.
```
[the remark this answers is not in the document]
Comment (IngelaAndin) [reply lib/ssl/src/tls_socket.erl]: Was undecisive  if it was worth it or not so sure.

File: lib/ssl/src/tls_socket.erl [hunk 2]
```diff
@@ -140,11 +140,14 @@ connect(Address, Port,
...
-	    {error, {options, {socket_options, UserOpts}}};
-	exit:{badarg, _} ->
-	    {error, {options, {socket_options, UserOpts}}}
+            ConStr = lists:flatten(io_lib:format("~p:connect(~p, ~p, ~p, ~p)", [Transport,Host, Port, UserOpts, Timeout])),
+	    {error, {badarg, ConStr}};
+        exit:badarg ->
+            ConStr = lists:flatten(io_lib:format("~p:connect(~p, ~p, ~p, ~p)", [Transport,Host, Port, UserOpts, Timeout])),
+	    {error, {badarg, ConStr}};
+	exit:{badarg, Reason} ->
+            ConStr = lists:flatten(io_lib:format("~p:connect(~p, ~p, ~p, ~p)", [Transport,Host, Port, UserOpts, Timeout])),
```
[the remark this answers is not in the document]
Comment (IngelaAndin) [reply lib/ssl/src/tls_socket.erl]: fixed

File: lib/ssl/src/tls_socket.erl [hunk 3]
```diff
@@ -140,11 +140,14 @@ connect(Address, Port,
 	    {error, Reason}
     catch
 	exit:{function_clause, _} ->
-	    {error, {options, {cb_info, CbInfo}}};
-	exit:badarg ->
-	    {error, {options, {socket_options, UserOpts}}};
-	exit:{badarg, _} ->
-	    {error, {options, {socket_options, UserOpts}}}
+            ConStr = lists:flatten(io_lib:format("~p:connect(~p, ~p, ~p, ~p)", [Transport,Host, Port, UserOpts, Timeout])),
+	    {error, {badarg, ConStr}};
```
[the remark this answers is not in the document]
Comment (IngelaAndin) [reply lib/ssl/src/tls_socket.erl]: A function clause here would be because of a badarg error.

File: lib/ssl/src/tls_socket.erl [hunk 4]
```diff
@@ -141,13 +141,16 @@ connect(Address, Port,
...
-	    {error, {options, {socket_options, UserOpts}}}
+	    {error, {badarg, connect_error(Transport, Host, Port, UserOpts, Timeout)}};
+        exit:badarg ->
+	    {error, {badarg, connect_error(Transport, Host, Port, UserOpts, Timeout)}};
+	exit:{badarg, Reason} ->
+	    {error, {badarg, connect_error(Transport, Host, Port, UserOpts, Timeout), Reason}}
     end.
 
+connect_error(Transport, Host, Port, UserOpts, Timeout) ->
+    ConStr = lists:flatten(io_lib:format("~p:connect(~p, ~p, ~p, ~p)", [Transport, Host, Port, UserOpts, Timeout])).
```
Comment (u3s) [inline lib/ssl/src/tls_socket.erl]: ConStr - not needed variable?
Apply 100 chars limit per line?

File: lib/ssl/src/tls_socket.erl [hunk 5]
```diff
@@ -141,13 +141,16 @@ connect(Address, Port,
 	    {error, Reason}
     catch
 	exit:{function_clause, _} ->
-	    {error, {options, {cb_info, CbInfo}}};
-	exit:badarg ->
-	    {error, {options, {socket_options, UserOpts}}};
-	exit:{badarg, _} ->
-	    {error, {options, {socket_options, UserOpts}}}
+	    {error, {badarg, connect_error(Transport, Host, Port, UserOpts, Timeout)}};
```
Comment (u3s) [inline lib/ssl/src/tls_socket.erl:151]: does not compile. Host variable is unbound.

Comment (IngelaAndin) [reply lib/ssl/src/tls_socket.erl:151]: Humm .. missed it as it was a small refactor and  github actions did not compile due to unexpected merge conflict. Renamed Address variable of surrounding function to Host.

File: lib/ssl/src/tls_socket.erl (hunk 4 above)
Comment (IngelaAndin) [reply lib/ssl/src/tls_socket.erl]: Now leftover form previous solution. Fixed both comments.
