### PR TITLE
Eliminate the set_tuple_element instruction

### LINKED ISSUE #10125: Useless emission of a `set_tuple_element` opcode
**Describe the bug**
There seems to be a bug in the set_tuple_element optimization in OTP28. If there are two `setelement/3` calls, the compiler generates two setelement/3 calls and one `set_tuple_element`. Either one of the `setelement/3` calls or the `set_tuple_element` look superfluous.

**To Reproduce**

```erlang
-module(test_set_tuple_element).
-export([id/1, test_set_tuple_element_op/0]).
id(X) -> X.

test_set_tuple_element_op() ->
    State0 = id({state, a, b, c, d, e, f, g}),
    State1 = setelement(6, State0, id([r1, r2, r8, r9]) -- [r8, r9]),
    State2 = setelement(8, State1, [r8, r9]),
    State3 = id(State2),
    [r8, r9] = element(8, State3),
    [r1, r2] = element(6, State3),
    ok.
```

This yields the following code:
```erlang
{function, test_set_tuple_element_op, 0, 15}.
  {label,14}.
    {line,[{location,"../tests/erlang_tests/test_set_tuple_element.erl",61}]}.
    {func_info,{atom,test_set_tuple_element},
               {atom,test_set_tuple_element_op},
               0}.
  {label,15}.
    {allocate,2,0}.
    {init_yregs,{list,[{y,0},{y,1}]}}.
    {move,{literal,{state,a,b,c,d,e,f,g}},{x,0}}.
    {line,[{location,"../tests/erlang_tests/test_set_tuple_element.erl",62}]}.
    {call,1,{f,13}}. % id/1
    {move,{x,0},{y,1}}.
    {move,{literal,[r1,r2,r8,r9]},{x,0}}.
    {line,[{location,"../tests/erlang_tests/test_set_tuple_element.erl",63}]}.
    {call,1,{f,13}}. % id/1
    {move,{literal,[r8,r9]},{x,1}}.
    {call_ext,2,{extfunc,erlang,'--',2}}.
    {move,{x,0},{y,0}}.
    {move,{y,1},{x,1}}.
    {move,{x,0},{x,2}}.
    {move,{integer,6},{x,0}}.
    {call_ext,3,{extfunc,erlang,setelement,3}}.
    {move,{y,1},{x,1}}.
    {move,{literal,[r8,r9]},{x,2}}.
    {init_yregs,{list,[{y,1}]}}.
    {move,{integer,8},{x,0}}.
    {line,[{location,"../tests/erlang_tests/test_set_tuple_element.erl",64}]}.
    {call_ext,3,{extfunc,erlang,setelement,3}}.
    {set_tuple_element,{y,0},{x,0},5}.
    {trim,2,0}.
    {line,[{location,"../tests/erlang_tests/test_set_tuple_element.erl",65}]}.
    {call,1,{f,13}}. % id/1
    {line,[{location,"../tests/erlang_tests/test_set_tuple_element.erl",66}]}.
    {bif,element,{f,0},[{integer,8},{x,0}],{x,1}}.
    {test,is_eq_exact,{f,17},[{x,1},{literal,[r8,r9]}]}.
    {get_tuple_element,{x,0},5,{x,0}}.
    {test,is_eq_exact,{f,16},[{x,0},{literal,[r1,r2]}]}.
    {move,{atom,ok},{x,0}}.
    {deallocate,0}.
    return.
  {label,16}.
    {line,[{location,"../tests/erlang_tests/test_set_tuple_element.erl",67}]}.
    {badmatch,{x,0}}.
  {label,17}.
    {line,[{location,"../tests/erlang_tests/test_set_tuple_element.erl",66}]}.
    {badmatch,{x,1}}.
```

Result of first call to `setelement/3` is ignored. So two tuples are allocated and we don't benefit entirely from the `set_tuple_element` optimization.

**Expected behavior**
Only one call to `setelement/3` should happen or we shouldn't have any use of `set_tuple_element`.

**Affected versions**
Tested with OTP28 compiler.

### PR DESCRIPTION
**Pull request by bjorng**
The `set_tuple_element` instruction was used before OTP 26 to optimize chains of `setelement/3` calls. For example:

    foo(S0) when tuple_size(S0) =:= 8 ->
        S1 = setelement(8, S0, a),
        S2 = setelement(7, S1, b),
        setelement(5, S2, c).

The compiler would keep the first call to `setelement/3` and replace the other two with `set_tuple_element`, which would destructively update the tuple created by the `setelement/3` call.

Starting in OTP 26, this was changed so that all three `setelement/3` calls are replaced with a single `update_record` instruction.

The `set_tuple_element` instruction was only used when the size of the tuple being updated was not known at compile time, as in the following example:

    bar(S0) ->
        S1 = setelement(8, S0, a),
        S2 = setelement(7, S1, b),
        setelement(5, S2, c).

The only difference compared to the previous example is that the type of `S0` is not known. When the size of the tuple cannot be determined at compile time, the compiler cannot use `update_record` and must fall back to `setelement/3` and `set_tuple_element`. However, the way this fallback was implemented caused extra useless instructions to be generated (see #10125 for examples).

This commit eliminates the use of `set_tuple_element` in the fallback path, allowing us to remove some particularly messy code from `beam_validator`.

Resolves #10125

### CODE REVIEW

**Comment by michalmuskala** [comment]
Do the sequences of `setelement` can take advantage of the mutability optimisation?

**Comment by bjorng** [comment]
> Do the sequences of `setelement` can take advantage of the mutability optimisation?

No. Optimization of `setelement` is only done when the size of the tuple is known at compile time. My pull request only handles tuples whose size are not known. When the size is not known, every `setelement` call is kept, but before this pull request additional useless `set_tuple_element` instructions were added. My pull request suppresses those extra instructions to reduce the code size.

File: erts/emulator/beam/jit/arm/instr_common.cpp [hunk 1]
```diff
@@ -1102,6 +1102,11 @@ void BeamModuleAssembler::emit_update_record_in_place(
 void BeamModuleAssembler::emit_set_tuple_element(const ArgSource &Element,
                                                  const ArgRegister &Tuple,
                                                  const ArgWord &Offset) {
+    /* TODO: As of Erlang/OTP 29, this instruction is no longer
+     * emitted by the compiler. It can be removed when the runtime
+     * system no longer supports loading code compiled by Erlang/OTP
```
Comment (pguyot) [inline erts/emulator/beam/jit/arm/instr_common.cpp:1107]: Thank you for this!

**Review by lucioleKi — APPROVED** [review]

File: lib/compiler/src/beam_validator.erl [hunk 2]
```diff
@@ -204,8 +204,6 @@ validate_0([{function, Name, Arity, Entry, Code} | Fs], Module, Level, Ft) ->
          hf=0,
          %% List of hot catch/try tags
          ct=[],
-         %% Previous instruction was setelement/3.
-         setelem=false,
```
Comment (jhogberg) [inline lib/compiler/src/beam_validator.erl:208]: We can do a drive-by removal of `puts_left` too, it's not used anywhere.

**Review by jhogberg — APPROVED** [review]

File: lib/compiler/src/beam_validator.erl (hunk 2 above)
Comment (bjorng) [reply lib/compiler/src/beam_validator.erl:208]: Good idea. Done.
