### PR TITLE
SSL: Fix connection problems in RC3

### LINKED ISSUE #11018: OTP 29.0-rc3: Can't reach erlang.org, fastly.com
**Describe the bug**
On OTP 29.0-rc2 this works:

```sh
$ erl -noshell -eval 'application:ensure_all_started([inets, ssl]), erlang:display(element(1, httpc:request("https://erlang.org"))), halt()'
ok
```

On OTP 29.0-rc3 this errors:

```sh
$ erl -noshell -eval 'application:ensure_all_started([inets, ssl]), erlang:display(httpc:request("https://erlang.org")), halt()'
=NOTICE REPORT==== 15-Apr-2026::15:52:43.707635 ===
TLS client: In state hello received SERVER ALERT: Fatal - Decode Error

{error,{failed_connect,[{to_address,{"erlang.org",443}},{inet,[inet],{tls_alert,{decode_error,"TLS client: In state hello received SERVER ALERT: Fatal - Decode Error\n"}}}]}}
```

**Affected versions**
OTP-29.0-rc3

### PR DESCRIPTION
**Pull request by dgud**
ssl: Fix default signature_algs causing connection failures                                                                                 
                                                                                                                                              
  The default signature_algorithms extension in the ClientHello had two                                                                       
  issues causing connections to fail with certain servers:                                                                                    
                                                                                                                                              
  1. Duplicate code points: When both TLS 1.3 and 1.2 were configured,                                                                        
     default_signature_algs/1 appended legacy {hash,sign} tuples (e.g.                                                                        
     {sha256,ecdsa}) that encode to the same wire values as the scheme                                                                        
     atoms already in the list (e.g. ecdsa_secp256r1_sha256). Strict                                                                          
     servers such as erlang.org rejected this with a decode error.                                                                            
                                                                                                                                              
  2. Unsupported PQ algorithms: The ML-DSA and SLH-DSA signature schemes                                                                      
     were included unconditionally without checking crypto support,                                                                           
     bloating the extension and causing servers with size limits (e.g.                                                                        
     fastly.com) to close the connection.                                                                                                     
                                                                                                                                              
  Fix by removing the redundant legacy ECDSA tuples from the TLS 1.3+1.2                                                                      
  default, filtering PQ schemes against crypto:supports(public_keys) in                                                                       
  signature_schemes/2, and prioritizing the fastest SLH-DSA variant while                                                                     
  moving the rest to the end of the default list.
  
  Fixes #11018

### CODE REVIEW

File: lib/ssl/src/tls_v1.erl [hunk 1]
```diff
@@ -944,114 +927,59 @@ default_signature_algs([?TLS_1_2 = Version |_]) ->
...
 signature_schemes(_, _) ->
     [].
 
 default_signature_schemes(Version) ->
-    Default = [mldsa87,
-               mldsa65,
-               mldsa44] ++ slh_dsa_schemes() ++
-        [eddsa_ed25519,
-         eddsa_ed448,
+    [GoodSLH|SLH_DSA] = slh_dsa_schemes(),
```
Comment (u3s) [inline lib/ssl/src/tls_v1.erl:978]: ### 4.4 AP-4: Variable Name `GoodSLH`

**WHY:** The name is informal and doesn't convey intent. The pattern
`[GoodSLH|SLH_DSA] = slh_dsa_schemes()` couples the default ordering
to the first element of `slh_dsa_schemes/0` — if someone reorders
that list, the "fastest" variant silently changes.

**WHAT:** `tls_v1.erl`, `default_signature_schemes/1`, line ~978.

**HOW:** Rename to `FastestSLH` or `PreferredSLH`. Add a comment
linking the choice to `slh_dsa_schemes/0` ordering.

File: lib/ssl/src/tls_v1.erl [hunk 2]
```diff
@@ -944,114 +927,59 @@ default_signature_algs([?TLS_1_2 = Version |_]) ->
...
+                            end,
+                     sets:is_element(Sign, PubKeys)
+                         andalso proplists:get_bool(Hash, Hashes)
+                         andalso is_pair(Hash, Sign0, Hashes)
+             end,
+    lists:filter(Filter, SignatureSchemes);
 signature_schemes(_, _) ->
     [].
 
 default_signature_schemes(Version) ->
```
Comment (u3s) [inline lib/ssl/src/tls_v1.erl:977]: ### 4.6 AP-6: Fastly Interop Comment

**WHY:** The ordering in `default_signature_schemes/1` looks arbitrary.
Without a comment, a future developer could move more PQC algorithms
before `rsa_pss_rsae_*` and re-break Fastly-hosted services (including
hex.pm, the BEAM ecosystem's package registry).

**WHAT:** `tls_v1.erl`, `default_signature_schemes/1`, line ~978.

**HOW:** Add above the default list:
```erlang
%% NOTE: Fastly CDN (serving hex.pm) has a PQC penalty bug in its
%% TLS 1.3 signature_algorithms parsing. Connections fail when BOTH:
%%   1. >=5 PQC code points (ML-DSA/SLH-DSA) appear before rsa_pss_rsae_*
%%   2. The first rsa_pss_rsae_* is at position >=17
%% Current layout: 4 PQC before rsae at position 16 (double margin).
%% Do not add PQC schemes before the traditional block. See PR-11056.
```

**Review by u3s — APPROVED** [review]

**Review by IngelaAndin — APPROVED** [review]
