### PR TITLE
Ingela/public key/ocsp/otp 19905

### LINKED ISSUE #10474: `public_key:der_encode('OCSPRequest', Request)` is not supported
**Describe the bug**

I don't understand why `'OCSPRequest'` was left out from `public_key:get_asn1_module/1`.
https://github.com/erlang/otp/blob/aa10ffdb1908bf57786a3f35a4c1dfec46571f10/lib/public_key/src/public_key.erl#L723-L726

If it was just accidentally missed, please consider adding it.

**Expected behavior**

`public_key:der_encode/2` can be used to encode OCSP request.

**Affected versions**

28

### PR DESCRIPTION
**Pull request by IngelaAndin**
Closes #10474

### CODE REVIEW

File: lib/public_key/src/public_key.erl [hunk 1]
```diff
@@ -659,6 +659,7 @@ get_asn1_module('AuthorityKeyIdentifier') -> 'PKIX1Implicit-2009';
 get_asn1_module('BasicConstraints') -> 'PKIX1Implicit-2009';
 get_asn1_module('ExtKeyUsageSyntax') -> 'PKIX1Implicit-2009';
 get_asn1_module('KeyUsage') -> 'PKIX1Implicit-2009';
+get_asn1_module('KeyIdentifier') -> 'PKIX1Implicit';
```
Comment (dgud) [inline lib/public_key/src/public_key.erl]: Why this change, and there is no `PKIX1Implicit`  missing "-2009" so these doesn't seem to be tested.

Comment (IngelaAndin) [reply lib/public_key/src/public_key.erl]: I will make some property based test to get some better coverage.  I noticed it was wrong, and will add "-2009", because I made some effort to add all subtypes from generated ASN-1 files that are included in generated encode functions first, but that was a huge job and I do not think that is actually needed.  It has however proved hard to find the exact set of generated encode/decode functions that are needed as the old solution more or less implicitly exposed everything which is no longer the case.
