### PR TITLE
JIT: Fix incorrect code generation for div/rem sequence

### LINKED ISSUE #5401: JIT generates incorrect code for some `div` and `rem` sequences
The JIT generates incorrect code. (Unsafe fusing of `intdiv` and `rem` instructions when registers have type information.)

Thanks to @itssundeep for [noticing this problem](https://github.com/erlang/otp/pull/5316#issuecomment-970867333).

**To Reproduce**
```
-module(bug).
-export([test/0,usec_to_time/1]).

test() ->
    {1,530342,0} = usec_to_time(1530342000*1000),
    ok.

usec_to_time(Usec) ->
    Us = Usec rem 1000000,
    Sec = (Usec div 1000000) rem 1000000,
    MegaSec = (Usec div 1000000) div 1000000,
    {MegaSec, Sec, Us}.
```

```
1> c(bug).
{ok,bug}
2> bug:test().
** exception error: no match of right hand side value {1,0,0}
     in function  bug:test/0 (bug.erl, line 5)
```

**Expected behavior**
```
1> c(bug).
{ok,bug}
2> bug:test().
ok
```
**Affected versions**
The `master` branch after the merge of #5316.

### PR DESCRIPTION
**Pull request by bjorng**
The type-based optimizations introduced in 3617610fbc40 (#5316) could
cause `divint` and `rem` instructions to be fused when it was not
safe.

Closes #5401.

### CODE REVIEW

**Review by garazdawi — APPROVED** [review]

File: erts/emulator/test/op_SUITE.erl [hunk 1]
```diff
@@ -424,6 +425,20 @@ eval(E0) ->
...
+
+usec_to_time(Usec) ->
+    Us = Usec rem 1000000,
+
+    %% div and rem would be fused, which is wrong since rem should use
+    %% the result of the div.
+    Sec = (Usec div 1000000) rem 1000000,
+    MegaSec = (Usec div 1000000) div 1000000,
+    {MegaSec, Sec, Us}.
+
```
Comment (max-au) [inline erts/emulator/test/op_SUITE.erl:441]: Can it be simplified to just `(Usec div 1000000) rem 1000000`?
(Us and MegaSec don't seem to make a difference).

Comment (bjorng) [reply erts/emulator/test/op_SUITE.erl]: Yes, it can be simplified. I also added a better explanation of what caused the bug.
