### PR TITLE
timer: Don't silently ignore errors when spawning processes

### LINKED ISSUE #7606: timer:apply_after(...) timers may never be executed if there is a problem spawning a process
**Describe the bug**
timer:apply_after(...) timers may never be executed if there is a problem spawning a process.

**To Reproduce**

1. Hit the max process system limit.
2. Setup a timer via timer:apply_after(...)
3. Wait for timer to fire (it never does as it cannot spawn a process to run the function)

**Expected behavior**
The timer eventually fires when the issue causing us to hit the spawn error (system limit) is removed, i.e:

1. Hit the max process system limit
2. Setup a timer via timer:apply_after(...)
3. Wait for some time for timer to fire (it will not)
4. Fix max process system limit issue (kill some processes)
5. Timer fires

**Affected versions**
All, as far as I am aware. The code was refactored in Erlang/OTP 26 - https://github.com/erlang/otp/commit/f9460ed7d09b44bdf559a42e5880d7f28d81f181 - but the previous code looks to hit the same issue. 

Prior to Erlang/OTP 19 only:
Quite interestingly, timer:apply_after(...) was used in supervisor.erl prior to Erlang/OTP 19 if a restart of a process failed. Were a user to hit the process system_limit, and a process were to crash, then the supervisor would attempt to restart it and that would fail. It would setup the timer which would also fail to spawn a process and the child would never be restarted. The timer:apply_after(...) call was removed in this change - https://github.com/erlang/otp/commit/44d5789619c70863af918ee5e2bdd7d411e68e80.

**Additional context**

I've only been able to hit this after hitting the max process limit, I'm unsure if there are other scenarios in which spawn may fail. Perhaps inability to allocate more memory?

Run test (run erl with +P 1024 to lower the max process count or this may take a while):
```
$ erl +P 1024
Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit] [dtrace]

Eshell V14.0.2 (press Ctrl+G to abort, type help(). for help)
1> compile:file(timer_test), l(timer_test), timer_test:simple_test().
```

Test Code:
```
-module(timer_test).

-include_lib("eunit/include/eunit.hrl").

-export([init/1, proc_wait/0, send_message/2]).

send_message(Pid, Message) ->
  Pid ! Message,
  ok.

proc_wait() ->
  Pid = spawn_link(fun () -> receive stop -> ok end end),
  {ok, Pid}.

init([]) ->
  {ok, {{one_for_one, 3, 10}, []}}.

simple_test() ->
  %% Sanity test, we can setup a timer, it will fire, a message will be sent to us and we can process it
  timer:apply_after(1, timer_test, send_message, [self(), sanity]),
  receive
    sanity -> ok
  end,

  %% Spin up a bunch of waiting processes to hit the process limit
  {ok, MaxProcSup} = supervisor:start_link(timer_test, []),
  lists:foreach(
    fun (X) ->
      supervisor:start_child(MaxProcSup,
                             #{id => X,
                               start => {timer_test, proc_wait, []},
                               shutdown => brutal_kill, restart => temporary})
    end,
    lists:seq(1, erlang:system_info(process_limit))),

  %% Setup our timer and wait for the message
  timer:apply_after(2, timer_test, send_message, [self(), test_message]),

  %% We expect to get hit the after clause after 10s as we the timer doesn't properly fire
  receive
    test_message ->
      %% Never expect to hit this
      ?assert(false)
  after 5000 ->
    %% Remove all the processes causing us to hit the system limit
    ChildProcesses = supervisor:which_children(MaxProcSup),
    lists:foreach(
      fun({_, ChildPid, _,_}) ->
        ChildPid ! stop
      end, ChildProcesses),

    %% New timer spawn sanity test
    timer:apply_after(1, timer_test, send_message, [self(), sanity2]),
    receive
      sanity2 -> ok
    end,

    receive
      test_message -> ok
    after 5000 ->
      %% Still not seen the original timer fire, fail the test
      ?assert(false)
    end
  end.
```

### PR DESCRIPTION
**Pull request by bjorng**
When a timer created by `timer` had expired and it was time to spawn a process to apply a user function, a `system_limit` exception (indicating that the limit for the number of processes in the system had been reached) would be silently ignored.

Since there is not really anything that can be done in this situation, be sure to terminate the system so that the problem is noticed. Note that that other parts of OTP don't attempt to cope with the failure to spawn processes because of a `system_limit` exception.

Fixes #7606

### CODE REVIEW

**Comment by juhlig** [comment]
Doesn't this make things worse, in reference to #7606? The OP of the issue was complaining about a non-firing timer. With this change, not catching `exit:process_limit`, the timer server will crash, so all timers it hosts will be lost, which is worse. Also, the timer server is a child of `kernel_sup`, and I understand that this means that when it crashes the whole node will crash?

**Review by rickard-green — APPROVED** [review]

File: lib/stdlib/src/timer.erl [hunk 1]
```diff
@@ -601,12 +601,12 @@ do_apply({erlang, exit, [Name, Reason]}, _) ->
 do_apply({M,F,A}, false) ->
     try spawn(M, F, A)
     of _ -> {ok, spawn}
-    catch _:_ -> error
+    catch error:badarg -> error
```
Comment (juhlig) [inline lib/stdlib/src/timer.erl:604]: I just noticed... `spawn` only fails with `badarg` if the arguments are _way_ off, ie if `M` or `F` are not atoms or if `A` is not a list. Pretty much everything else, like the length of `A` not matching the arity of `M:F`, will not cause any exception thrown by the `spawn` itself, but instead a process _will_ be started and the exception will be raised from there.

Given that it is impossible (famous last words :sweat_smile:) to start `apply_*` timers where `M` and `F` are _not_ atoms or where `A` is _not_ a list ***when going through the `timer` API functions***, ie without (deliberately) ***bypassing*** them by sending messages to the timer server directly, maybe the `spawn`s should not be wrapped in `try ... catch`es at all?

Comment (bjorng) [reply lib/stdlib/src/timer.erl:604]: Yes, the try/catch is probably unnecessary. Since the PR targeted a patch release, I kept the try/catch just in case to minimize the risk of introducing a bug.
